In [18]:
from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Optional, Set

import numpy as np
import pandas as pd
from pymongo import MongoClient
import yaml

In [19]:
def load_config(path: str | Path = "../config/config.yaml") -> dict[str, Any]:
    path = Path(path)
    if not path.exists():
        path = Path("config/config.yaml")
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


config = load_config()
mongo_config = config["mongo"]

In [23]:
client = MongoClient(mongo_config.get('url'))
db = client[mongo_config.get('db')]
col_schedule = db[mongo_config.get('collection').get('collection_schedule')]
df_schedule = pd.DataFrame(col_schedule.find({'season': config.get("season").get("year")}))
check_games = df_schedule['game_id'].sample(5, random_state=1909).values.tolist()

In [25]:
col_team_stats = db[mongo_config.get('collection').get('collection_team_game_stats')]
col_player_stats = db[mongo_config.get('collection').get('collection_player_game_stats')]

df_team_stats = pd.DataFrame(col_team_stats.find({'game_id': {"$in": check_games}}))
df_player_stast = pd.DataFrame(col_player_stats.find({'game_id': {"$in": check_games}}))

In [26]:
pd.set_option("display.max_rows", None)

for game in check_games:
    team_stats = df_team_stats[df_team_stats.game_id == game]
    team_stats = team_stats.sort_values(by='game_venue', ascending=False).reset_index(drop=True)
    game_info = team_stats[['game_id', 'game_date', 'week', 'team_name', 'game_venue']]
    stats = pd.json_normalize(team_stats.stats)
    stats_df = stats[[col for col in stats.columns if 'ft.' in col]]
    
    final_game = pd.merge(
        game_info,
        stats_df,
        left_index=True,
        right_index=True
    )
    display(final_game.T)
    print("\n" + "-" * 80 + "\n")

,0,1
game_id,1910804,1910804
game_date,2026-01-14 17:30:00,2026-01-14 17:30:00
week,17,17
team_name,Wolfsburg,St. Pauli
game_venue,home,away
ft.possession,0.608616,0.391384
ft.goals,2,1
ft.shots,13,9
ft.shot_goal,2,1
ft.shot_on_target,5,4
ft.shot_off_target,4,4
ft.shot_woodwork,0,0
ft.shot_blocked,4,1
ft.shot_own_goal,0,0
ft.shot_zone_6_yard_box,1,3
ft.shot_zone_penalty_area,8,1
ft.shot_zone_outside_box,4,5
ft.shot_open_play,8,6
ft.shot_fastbreak,1,2
ft.shot_set_piece,3,1
ft.shot_penalty,1,0
ft.shot_right_foot,3,8
ft.shot_left_foot,5,1
ft.shot_head,5,0
ft.shot_other_body_part,0,0
ft.pass_attempt,664,427
ft.pass_completed,565,328
ft.pass_cross,25,12
ft.pass_freekick,7,13
ft.pass_corner,7,4
ft.pass_through_ball,0,0
ft.pass_throw_in,16,16
ft.pass_key_pass,12,5
ft.pass_assist,1,1
ft.pass_long,68,58
ft.pass_short,596,369
ft.pass_chipped,62,32
ft.pass_ground,602,395
ft.pass_head,30,34
ft.pass_feet,634,393
ft.pass_forward,397,278
ft.pass_backward,264,149
ft.pass_left,345,212
ft.pass_right,315,212
ft.pass_defensive_third,110,133
ft.pass_mid_third,361,193
ft.pass_final_third,193,101
ft.dribbles,17,13
ft.dribble_successful,6,7
ft.dribble_unsuccessful,11,6
ft.tackles_attempted,20,24
ft.tackle_gained_possession,6,9
ft.tackle_did_not_get_possession,7,9
ft.tackle_was_dribbled,7,6
ft.interceptions,5,5
ft.clearances,13,30
ft.clearance_head,5,17
ft.clearance_feet,8,13
ft.blocks,10,12
ft.blocked_shot,1,3
ft.blocked_cross,9,9
ft.offsides,4,2
ft.foul_committed,10,9
ft.foul_suffered,9,10
ft.aerial_duels,33,33
ft.aerial_duel_won,18,15
ft.aerial_duel_lost,15,18
ft.touches,791,568
ft.loss_of_possession,18,22
ft.dispossessed,7,8
ft.turnover,11,14
ft.errors,1,0
ft.error_leading_to_shot,1,0
ft.error_leading_to_goal,0,0
ft.goalkeeper_actions,7,9
ft.saves,3,3
ft.claims,0,0
ft.punches,0,0
ft.keeper_pickup,3,6
ft.keeper_sweeper,1,0
ft.ball_recoveries,41,37
ft.cards,1,2
ft.yellow_card,1,2
ft.second_yellow_card,0,0
ft.red_card,0,0
ft.pass_cross_completed,8,4
ft.pass_long_completed,42,22
ft.pass_short_completed,523,306
ft.pass_chipped_completed,27,16
ft.pass_ground_completed,538,312
ft.pass_head_completed,18,16
ft.pass_feet_completed,547,312
ft.pass_forward_completed,318,192
ft.pass_backward_completed,244,136
ft.pass_left_completed,290,168
ft.pass_right_completed,273,159
ft.pass_defensive_third_completed,107,125
ft.pass_mid_third_completed,331,141
ft.pass_final_third_completed,127,62
ft.shot_zone_inside_box,9,4
ft.shot_foot,8,9
ft.shot_accuracy,0.384615,0.444444
ft.goal_conversion_pct,0.153846,0.111111
ft.shot_on_target_conversion_pct,0.4,0.25
ft.shot_blocked_pct,0.307692,0.111111
ft.shot_outside_box_pct,0.307692,0.555556
ft.shot_inside_box_pct,0.692308,0.444444
ft.shot_6_yard_box_pct,0.076923,0.333333
ft.shot_penalty_area_pct,0.615385,0.111111
ft.shot_open_play_pct,0.615385,0.666667
ft.shot_fastbreak_pct,0.076923,0.222222
ft.shot_set_piece_pct,0.230769,0.111111
ft.shot_penalty_pct,0.076923,0.0
ft.shot_foot_pct,0.615385,1.0
ft.shot_right_foot_pct,0.375,0.888889
ft.shot_left_foot_pct,0.625,0.111111
ft.shot_head_pct,0.384615,0.0
ft.shot_other_body_part_pct,0.0,0.0
ft.pass_completion_pct,0.850904,0.76815
ft.pass_cross_completion_pct,0.32,0.333333
ft.pass_long_pct,0.10241,0.135831
ft.pass_short_pct,0.89759,0.864169
ft.pass_long_completion_pct,0.617647,0.37931
ft.pass_short_completion_pct,0.877517,0.829268
ft.pass_chipped_pct,0.093373,0.074941
ft.pass_ground_pct,0.906627,0.925059
ft.pass_chipped_completion_pct,0.435484,0.5
ft.pass_ground_completion_pct,0.893688,0.789873
ft.pass_head_pct,0.045181,0.079625
ft.pass_feet_pct,0.954819,0.920375
ft.pass_head_completion_pct,0.6,0.470588
ft.pass_feet_completion_pct,0.862776,0.793893
ft.pass_forward_pct,0.597892,0.651054
ft.pass_backward_pct,0.39759,0.348946
ft.pass_forward_completion_pct,0.801008,0.690647
ft.pass_backward_completion_pct,0.924242,0.912752
ft.pass_left_pct,0.519578,0.496487
ft.pass_right_pct,0.474398,0.496487
ft.pass_left_completion_pct,0.84058,0.792453
ft.pass_right_completion_pct,0.866667,0.75
ft.pass_defensive_third_pct,0.165663,0.311475
ft.pass_mid_third_pct,0.543675,0.451991
ft.pass_final_third_pct,0.290663,0.236534
ft.pass_defensive_third_completion_pct,0.972727,0.93985
ft.pass_mid_third_completion_pct,0.916898,0.73057
ft.pass_final_third_completion_pct,0.658031,0.613861
ft.dribble_success_pct,0.352941,0.538462
ft.tackle_success_pct,0.3,0.375
ft.aerial_duel_win_pct,0.545455,0.454545
ft.loss_possession_dispossessed_pct,0.388889,0.363636
ft.loss_possession_turnover_pct,0.611111,0.636364

--------------------------------------------------------------------------------

,0,1
game_id,1910777,1910777
game_date,2026-03-14 14:30:00,2026-03-14 14:30:00
week,26,26
team_name,Borussia Dortmund,Augsburg
game_venue,home,away
ft.possession,0.599613,0.400387
ft.goals,2,0
ft.shots,16,7
ft.shot_goal,2,0
ft.shot_on_target,5,3
ft.shot_off_target,7,4
ft.shot_woodwork,2,0
ft.shot_blocked,4,0
ft.shot_own_goal,0,0
ft.shot_zone_6_yard_box,3,1
ft.shot_zone_penalty_area,11,3
ft.shot_zone_outside_box,2,3
ft.shot_open_play,9,3
ft.shot_fastbreak,1,1
ft.shot_set_piece,6,3
ft.shot_penalty,0,0
ft.shot_right_foot,7,4
ft.shot_left_foot,3,2
ft.shot_head,6,1
ft.shot_other_body_part,0,0
ft.pass_attempt,620,414
ft.pass_completed,524,321
ft.pass_cross,27,6
ft.pass_freekick,9,6
ft.pass_corner,12,2
ft.pass_through_ball,6,1
ft.pass_throw_in,11,18
ft.pass_key_pass,14,5
ft.pass_assist,1,0
ft.pass_long,51,53
ft.pass_short,569,361
ft.pass_chipped,58,36
ft.pass_ground,562,378
ft.pass_head,31,17
ft.pass_feet,589,397
ft.pass_forward,375,268
ft.pass_backward,243,140
ft.pass_left,303,187
ft.pass_right,316,223
ft.pass_defensive_third,130,154
ft.pass_mid_third,307,186
ft.pass_final_third,183,74
ft.dribbles,17,9
ft.dribble_successful,9,5
ft.dribble_unsuccessful,8,4
ft.tackles_attempted,20,21
ft.tackle_gained_possession,8,6
ft.tackle_did_not_get_possession,7,6
ft.tackle_was_dribbled,5,9
ft.interceptions,14,10
ft.clearances,14,19
ft.clearance_head,10,10
ft.clearance_feet,4,9
ft.blocks,9,15
ft.blocked_shot,0,4
ft.blocked_cross,9,11
ft.offsides,0,3
ft.foul_committed,7,7
ft.foul_suffered,7,7
ft.aerial_duels,24,24
ft.aerial_duel_won,18,6
ft.aerial_duel_lost,6,18
ft.touches,755,546
ft.loss_of_possession,27,25
ft.dispossessed,6,11
ft.turnover,21,14
ft.errors,2,0
ft.error_leading_to_shot,2,0
ft.error_leading_to_goal,0,0
ft.goalkeeper_actions,13,20
ft.saves,3,3
ft.claims,1,2
ft.punches,0,5
ft.keeper_pickup,8,8
ft.keeper_sweeper,1,2
ft.ball_recoveries,45,41
ft.cards,0,0
ft.yellow_card,0,0
ft.second_yellow_card,0,0
ft.red_card,0,0
ft.pass_cross_completed,8,1
ft.pass_long_completed,23,18
ft.pass_short_completed,501,303
ft.pass_chipped_completed,29,15
ft.pass_ground_completed,495,306
ft.pass_head_completed,21,8
ft.pass_feet_completed,503,313
ft.pass_forward_completed,300,185
ft.pass_backward_completed,222,131
ft.pass_left_completed,263,141
ft.pass_right_completed,260,179
ft.pass_defensive_third_completed,127,135
ft.pass_mid_third_completed,281,144
ft.pass_final_third_completed,116,42
ft.shot_zone_inside_box,14,4
ft.shot_foot,10,6
ft.shot_accuracy,0.3125,0.428571
ft.goal_conversion_pct,0.125,0.0
ft.shot_on_target_conversion_pct,0.4,0.0
ft.shot_blocked_pct,0.25,0.0
ft.shot_outside_box_pct,0.125,0.428571
ft.shot_inside_box_pct,0.875,0.571429
ft.shot_6_yard_box_pct,0.1875,0.142857
ft.shot_penalty_area_pct,0.6875,0.428571
ft.shot_open_play_pct,0.5625,0.428571
ft.shot_fastbreak_pct,0.0625,0.142857
ft.shot_set_piece_pct,0.375,0.428571
ft.shot_penalty_pct,0.0,0.0
ft.shot_foot_pct,0.625,0.857143
ft.shot_right_foot_pct,0.7,0.666667
ft.shot_left_foot_pct,0.3,0.333333
ft.shot_head_pct,0.375,0.142857
ft.shot_other_body_part_pct,0.0,0.0
ft.pass_completion_pct,0.845161,0.775362
ft.pass_cross_completion_pct,0.296296,0.166667
ft.pass_long_pct,0.082258,0.128019
ft.pass_short_pct,0.917742,0.871981
ft.pass_long_completion_pct,0.45098,0.339623
ft.pass_short_completion_pct,0.880492,0.839335
ft.pass_chipped_pct,0.093548,0.086957
ft.pass_ground_pct,0.906452,0.913043
ft.pass_chipped_completion_pct,0.5,0.416667
ft.pass_ground_completion_pct,0.880783,0.809524
ft.pass_head_pct,0.05,0.041063
ft.pass_feet_pct,0.95,0.958937
ft.pass_head_completion_pct,0.677419,0.470588
ft.pass_feet_completion_pct,0.85399,0.788413
ft.pass_forward_pct,0.604839,0.647343
ft.pass_backward_pct,0.391935,0.338164
ft.pass_forward_completion_pct,0.8,0.690299
ft.pass_backward_completion_pct,0.91358,0.935714
ft.pass_left_pct,0.48871,0.451691
ft.pass_right_pct,0.509677,0.538647
ft.pass_left_completion_pct,0.867987,0.754011
ft.pass_right_completion_pct,0.822785,0.802691
ft.pass_defensive_third_pct,0.209677,0.371981
ft.pass_mid_third_pct,0.495161,0.449275
ft.pass_final_third_pct,0.295161,0.178744
ft.pass_defensive_third_completion_pct,0.976923,0.876623
ft.pass_mid_third_completion_pct,0.915309,0.774194
ft.pass_final_third_completion_pct,0.63388,0.567568
ft.dribble_success_pct,0.529412,0.555556
ft.tackle_success_pct,0.4,0.285714
ft.aerial_duel_win_pct,0.75,0.25
ft.loss_possession_dispossessed_pct,0.222222,0.44
ft.loss_possession_turnover_pct,0.777778,0.56

--------------------------------------------------------------------------------

,0,1
game_id,1910835,1910835
game_date,2026-02-07 14:30:00,2026-02-07 14:30:00
week,21,21
team_name,Freiburg,Werder Bremen
game_venue,home,away
ft.possession,0.334728,0.665272
ft.goals,1,0
ft.shots,7,17
ft.shot_goal,1,0
ft.shot_on_target,2,5
ft.shot_off_target,4,4
ft.shot_woodwork,0,0
ft.shot_blocked,1,8
ft.shot_own_goal,0,0
ft.shot_zone_6_yard_box,0,0
ft.shot_zone_penalty_area,5,9
ft.shot_zone_outside_box,2,8
ft.shot_open_play,4,10
ft.shot_fastbreak,1,1
ft.shot_set_piece,2,6
ft.shot_penalty,0,0
ft.shot_right_foot,4,10
ft.shot_left_foot,2,5
ft.shot_head,1,2
ft.shot_other_body_part,0,0
ft.pass_attempt,320,636
ft.pass_completed,217,516
ft.pass_cross,19,48
ft.pass_freekick,11,9
ft.pass_corner,4,8
ft.pass_through_ball,0,1
ft.pass_throw_in,19,29
ft.pass_key_pass,5,10
ft.pass_assist,1,0
ft.pass_long,55,61
ft.pass_short,265,575
ft.pass_chipped,31,79
ft.pass_ground,289,557
ft.pass_head,21,26
ft.pass_feet,299,610
ft.pass_forward,232,427
ft.pass_backward,84,208
ft.pass_left,161,316
ft.pass_right,158,319
ft.pass_defensive_third,52,108
ft.pass_mid_third,137,224
ft.pass_final_third,131,304
ft.dribbles,17,7
ft.dribble_successful,9,3
ft.dribble_unsuccessful,8,4
ft.tackles_attempted,14,24
ft.tackle_gained_possession,4,6
ft.tackle_did_not_get_possession,7,9
ft.tackle_was_dribbled,3,9
ft.interceptions,10,14
ft.clearances,50,25
ft.clearance_head,30,17
ft.clearance_feet,20,8
ft.blocks,20,16
ft.blocked_shot,8,1
ft.blocked_cross,12,15
ft.offsides,0,2
ft.foul_committed,9,12
ft.foul_suffered,12,9
ft.aerial_duels,34,34
ft.aerial_duel_won,17,17
ft.aerial_duel_lost,17,17
ft.touches,505,785
ft.loss_of_possession,22,24
ft.dispossessed,8,7
ft.turnover,14,17
ft.errors,2,1
ft.error_leading_to_shot,2,0
ft.error_leading_to_goal,0,1
ft.goalkeeper_actions,15,6
ft.saves,6,1
ft.claims,2,0
ft.punches,1,0
ft.keeper_pickup,6,5
ft.keeper_sweeper,0,0
ft.ball_recoveries,37,37
ft.cards,2,1
ft.yellow_card,1,1
ft.second_yellow_card,0,0
ft.red_card,1,0
ft.pass_cross_completed,2,11
ft.pass_long_completed,23,34
ft.pass_short_completed,194,482
ft.pass_chipped_completed,12,25
ft.pass_ground_completed,205,491
ft.pass_head_completed,7,14
ft.pass_feet_completed,210,502
ft.pass_forward_completed,148,327
ft.pass_backward_completed,66,188
ft.pass_left_completed,108,253
ft.pass_right_completed,108,263
ft.pass_defensive_third_completed,50,101
ft.pass_mid_third_completed,96,197
ft.pass_final_third_completed,71,218
ft.shot_zone_inside_box,5,9
ft.shot_foot,6,15
ft.shot_accuracy,0.285714,0.294118
ft.goal_conversion_pct,0.142857,0.0
ft.shot_on_target_conversion_pct,0.5,0.0
ft.shot_blocked_pct,0.142857,0.470588
ft.shot_outside_box_pct,0.285714,0.470588
ft.shot_inside_box_pct,0.714286,0.529412
ft.shot_6_yard_box_pct,0.0,0.0
ft.shot_penalty_area_pct,0.714286,0.529412
ft.shot_open_play_pct,0.571429,0.588235
ft.shot_fastbreak_pct,0.142857,0.058824
ft.shot_set_piece_pct,0.285714,0.352941
ft.shot_penalty_pct,0.0,0.0
ft.shot_foot_pct,0.857143,0.882353
ft.shot_right_foot_pct,0.666667,0.666667
ft.shot_left_foot_pct,0.333333,0.333333
ft.shot_head_pct,0.142857,0.117647
ft.shot_other_body_part_pct,0.0,0.0
ft.pass_completion_pct,0.678125,0.811321
ft.pass_cross_completion_pct,0.105263,0.229167
ft.pass_long_pct,0.171875,0.095912
ft.pass_short_pct,0.828125,0.904088
ft.pass_long_completion_pct,0.418182,0.557377
ft.pass_short_completion_pct,0.732075,0.838261
ft.pass_chipped_pct,0.096875,0.124214
ft.pass_ground_pct,0.903125,0.875786
ft.pass_chipped_completion_pct,0.387097,0.316456
ft.pass_ground_completion_pct,0.709343,0.881508
ft.pass_head_pct,0.065625,0.040881
ft.pass_feet_pct,0.934375,0.959119
ft.pass_head_completion_pct,0.333333,0.538462
ft.pass_feet_completion_pct,0.702341,0.822951
ft.pass_forward_pct,0.725,0.671384
ft.pass_backward_pct,0.2625,0.327044
ft.pass_forward_completion_pct,0.637931,0.765808
ft.pass_backward_completion_pct,0.785714,0.903846
ft.pass_left_pct,0.503125,0.496855
ft.pass_right_pct,0.49375,0.501572
ft.pass_left_completion_pct,0.670807,0.800633
ft.pass_right_completion_pct,0.683544,0.824451
ft.pass_defensive_third_pct,0.1625,0.169811
ft.pass_mid_third_pct,0.428125,0.352201
ft.pass_final_third_pct,0.409375,0.477987
ft.pass_defensive_third_completion_pct,0.961538,0.935185
ft.pass_mid_third_completion_pct,0.70073,0.879464
ft.pass_final_third_completion_pct,0.541985,0.717105
ft.dribble_success_pct,0.529412,0.428571
ft.tackle_success_pct,0.285714,0.25
ft.aerial_duel_win_pct,0.5,0.5
ft.loss_possession_dispossessed_pct,0.363636,0.291667
ft.loss_possession_turnover_pct,0.636364,0.708333

--------------------------------------------------------------------------------

,0,1
game_id,1910874,1910874
game_date,2026-04-26 14:30:00,2026-04-26 14:30:00
week,31,31
team_name,VfB Stuttgart,Werder Bremen
game_venue,home,away
ft.possession,0.682156,0.317844
ft.goals,1,1
ft.shots,20,9
ft.shot_goal,1,1
ft.shot_on_target,4,3
ft.shot_off_target,8,4
ft.shot_woodwork,0,0
ft.shot_blocked,8,2
ft.shot_own_goal,0,0
ft.shot_zone_6_yard_box,2,1
ft.shot_zone_penalty_area,7,8
ft.shot_zone_outside_box,11,0
ft.shot_open_play,13,6
ft.shot_fastbreak,0,2
ft.shot_set_piece,7,1
ft.shot_penalty,0,0
ft.shot_right_foot,11,5
ft.shot_left_foot,6,2
ft.shot_head,3,2
ft.shot_other_body_part,0,0
ft.pass_attempt,734,342
ft.pass_completed,624,254
ft.pass_cross,40,10
ft.pass_freekick,9,8
ft.pass_corner,14,2
ft.pass_through_ball,0,0
ft.pass_throw_in,24,15
ft.pass_key_pass,16,7
ft.pass_assist,1,1
ft.pass_long,46,63
ft.pass_short,688,279
ft.pass_chipped,66,28
ft.pass_ground,668,314
ft.pass_head,31,24
ft.pass_feet,703,318
ft.pass_forward,431,223
ft.pass_backward,300,118
ft.pass_left,384,159
ft.pass_right,347,178
ft.pass_defensive_third,108,99
ft.pass_mid_third,371,150
ft.pass_final_third,255,93
ft.dribbles,18,14
ft.dribble_successful,7,3
ft.dribble_unsuccessful,11,11
ft.tackles_attempted,16,28
ft.tackle_gained_possession,6,12
ft.tackle_did_not_get_possession,7,9
ft.tackle_was_dribbled,3,7
ft.interceptions,11,10
ft.clearances,6,36
ft.clearance_head,4,20
ft.clearance_feet,2,16
ft.blocks,13,27
ft.blocked_shot,2,8
ft.blocked_cross,11,19
ft.offsides,0,1
ft.foul_committed,8,10
ft.foul_suffered,10,8
ft.aerial_duels,32,32
ft.aerial_duel_won,15,17
ft.aerial_duel_lost,17,15
ft.touches,878,528
ft.loss_of_possession,29,21
ft.dispossessed,11,4
ft.turnover,18,17
ft.errors,1,2
ft.error_leading_to_shot,1,2
ft.error_leading_to_goal,0,0
ft.goalkeeper_actions,10,20
ft.saves,2,4
ft.claims,1,3
ft.punches,0,2
ft.keeper_pickup,7,11
ft.keeper_sweeper,0,0
ft.ball_recoveries,43,41
ft.cards,0,1
ft.yellow_card,0,1
ft.second_yellow_card,0,0
ft.red_card,0,0
ft.pass_cross_completed,6,4
ft.pass_long_completed,24,27
ft.pass_short_completed,600,227
ft.pass_chipped_completed,23,19
ft.pass_ground_completed,601,235
ft.pass_head_completed,18,12
ft.pass_feet_completed,606,242
ft.pass_forward_completed,350,143
ft.pass_backward_completed,272,110
ft.pass_left_completed,327,114
ft.pass_right_completed,296,138
ft.pass_defensive_third_completed,108,90
ft.pass_mid_third_completed,337,104
ft.pass_final_third_completed,179,60
ft.shot_zone_inside_box,9,9
ft.shot_foot,17,7
ft.shot_accuracy,0.2,0.333333
ft.goal_conversion_pct,0.05,0.111111
ft.shot_on_target_conversion_pct,0.25,0.333333
ft.shot_blocked_pct,0.4,0.222222
ft.shot_outside_box_pct,0.55,0.0
ft.shot_inside_box_pct,0.45,1.0
ft.shot_6_yard_box_pct,0.1,0.111111
ft.shot_penalty_area_pct,0.35,0.888889
ft.shot_open_play_pct,0.65,0.666667
ft.shot_fastbreak_pct,0.0,0.222222
ft.shot_set_piece_pct,0.35,0.111111
ft.shot_penalty_pct,0.0,0.0
ft.shot_foot_pct,0.85,0.777778
ft.shot_right_foot_pct,0.647059,0.714286
ft.shot_left_foot_pct,0.352941,0.285714
ft.shot_head_pct,0.15,0.222222
ft.shot_other_body_part_pct,0.0,0.0
ft.pass_completion_pct,0.850136,0.74269
ft.pass_cross_completion_pct,0.15,0.4
ft.pass_long_pct,0.06267,0.184211
ft.pass_short_pct,0.93733,0.815789
ft.pass_long_completion_pct,0.521739,0.428571
ft.pass_short_completion_pct,0.872093,0.81362
ft.pass_chipped_pct,0.089918,0.081871
ft.pass_ground_pct,0.910082,0.918129
ft.pass_chipped_completion_pct,0.348485,0.678571
ft.pass_ground_completion_pct,0.899701,0.748408
ft.pass_head_pct,0.042234,0.070175
ft.pass_feet_pct,0.957766,0.929825
ft.pass_head_completion_pct,0.580645,0.5
ft.pass_feet_completion_pct,0.86202,0.761006
ft.pass_forward_pct,0.587193,0.652047
ft.pass_backward_pct,0.408719,0.345029
ft.pass_forward_completion_pct,0.812065,0.641256
ft.pass_backward_completion_pct,0.906667,0.932203
ft.pass_left_pct,0.523161,0.464912
ft.pass_right_pct,0.472752,0.520468
ft.pass_left_completion_pct,0.851562,0.716981
ft.pass_right_completion_pct,0.853026,0.775281
ft.pass_defensive_third_pct,0.147139,0.289474
ft.pass_mid_third_pct,0.50545,0.438596
ft.pass_final_third_pct,0.347411,0.27193
ft.pass_defensive_third_completion_pct,1.0,0.909091
ft.pass_mid_third_completion_pct,0.908356,0.693333
ft.pass_final_third_completion_pct,0.701961,0.645161
ft.dribble_success_pct,0.388889,0.214286
ft.tackle_success_pct,0.375,0.428571
ft.aerial_duel_win_pct,0.46875,0.53125
ft.loss_possession_dispossessed_pct,0.37931,0.190476
ft.loss_possession_turnover_pct,0.62069,0.809524

--------------------------------------------------------------------------------

,0,1
game_id,1910843,1910843
game_date,2026-04-04 14:30:00,2026-04-04 14:30:00
week,28,28
team_name,Freiburg,Bayern Munich
game_venue,home,away
ft.possession,0.306186,0.693814
ft.goals,2,3
ft.shots,13,21
ft.shot_goal,2,3
ft.shot_on_target,4,9
ft.shot_off_target,5,5
ft.shot_woodwork,0,0
ft.shot_blocked,4,7
ft.shot_own_goal,0,0
ft.shot_zone_6_yard_box,3,2
ft.shot_zone_penalty_area,6,9
ft.shot_zone_outside_box,4,10
ft.shot_open_play,7,13
ft.shot_fastbreak,0,3
ft.shot_set_piece,6,5
ft.shot_penalty,0,0
ft.shot_right_foot,7,13
ft.shot_left_foot,4,7
ft.shot_head,2,1
ft.shot_other_body_part,0,0
ft.pass_attempt,297,673
ft.pass_completed,213,589
ft.pass_cross,21,13
ft.pass_freekick,11,12
ft.pass_corner,5,8
ft.pass_through_ball,1,0
ft.pass_throw_in,15,22
ft.pass_key_pass,10,17
ft.pass_assist,1,3
ft.pass_long,56,55
ft.pass_short,241,618
ft.pass_chipped,24,46
ft.pass_ground,273,627
ft.pass_head,21,21
ft.pass_feet,276,652
ft.pass_forward,201,396
ft.pass_backward,95,272
ft.pass_left,137,315
ft.pass_right,159,355
ft.pass_defensive_third,98,147
ft.pass_mid_third,103,292
ft.pass_final_third,96,234
ft.dribbles,18,23
ft.dribble_successful,9,6
ft.dribble_unsuccessful,9,17
ft.tackles_attempted,29,24
ft.tackle_gained_possession,12,10
ft.tackle_did_not_get_possession,11,5
ft.tackle_was_dribbled,6,9
ft.interceptions,12,10
ft.clearances,32,19
ft.clearance_head,9,6
ft.clearance_feet,23,13
ft.blocks,17,11
ft.blocked_shot,6,4
ft.blocked_cross,11,7
ft.offsides,4,1
ft.foul_committed,9,13
ft.foul_suffered,13,9
ft.aerial_duels,19,19
ft.aerial_duel_won,11,8
ft.aerial_duel_lost,8,11
ft.touches,480,825
ft.loss_of_possession,24,26
ft.dispossessed,7,11
ft.turnover,17,15
ft.errors,0,1
ft.error_leading_to_shot,0,0
ft.error_leading_to_goal,0,1
ft.goalkeeper_actions,18,8
ft.saves,6,2
ft.claims,0,0
ft.punches,3,0
ft.keeper_pickup,9,6
ft.keeper_sweeper,0,0
ft.ball_recoveries,44,43
ft.cards,3,3
ft.yellow_card,3,3
ft.second_yellow_card,0,0
ft.red_card,0,0
ft.pass_cross_completed,6,3
ft.pass_long_completed,23,36
ft.pass_short_completed,190,553
ft.pass_chipped_completed,12,20
ft.pass_ground_completed,201,569
ft.pass_head_completed,12,16
ft.pass_feet_completed,201,573
ft.pass_forward_completed,126,327
ft.pass_backward_completed,86,258
ft.pass_left_completed,100,274
ft.pass_right_completed,113,312
ft.pass_defensive_third_completed,90,141
ft.pass_mid_third_completed,65,266
ft.pass_final_third_completed,58,182
ft.shot_zone_inside_box,9,11
ft.shot_foot,11,20
ft.shot_accuracy,0.307692,0.428571
ft.goal_conversion_pct,0.153846,0.142857
ft.shot_on_target_conversion_pct,0.5,0.333333
ft.shot_blocked_pct,0.307692,0.333333
ft.shot_outside_box_pct,0.307692,0.47619
ft.shot_inside_box_pct,0.692308,0.52381
ft.shot_6_yard_box_pct,0.230769,0.095238
ft.shot_penalty_area_pct,0.461538,0.428571
ft.shot_open_play_pct,0.538462,0.619048
ft.shot_fastbreak_pct,0.0,0.142857
ft.shot_set_piece_pct,0.461538,0.238095
ft.shot_penalty_pct,0.0,0.0
ft.shot_foot_pct,0.846154,0.952381
ft.shot_right_foot_pct,0.636364,0.65
ft.shot_left_foot_pct,0.363636,0.35
ft.shot_head_pct,0.153846,0.047619
ft.shot_other_body_part_pct,0.0,0.0
ft.pass_completion_pct,0.717172,0.875186
ft.pass_cross_completion_pct,0.285714,0.230769
ft.pass_long_pct,0.188552,0.081724
ft.pass_short_pct,0.811448,0.918276
ft.pass_long_completion_pct,0.410714,0.654545
ft.pass_short_completion_pct,0.788382,0.894822
ft.pass_chipped_pct,0.080808,0.068351
ft.pass_ground_pct,0.919192,0.931649
ft.pass_chipped_completion_pct,0.5,0.434783
ft.pass_ground_completion_pct,0.736264,0.907496
ft.pass_head_pct,0.070707,0.031204
ft.pass_feet_pct,0.929293,0.968796
ft.pass_head_completion_pct,0.571429,0.761905
ft.pass_feet_completion_pct,0.728261,0.878834
ft.pass_forward_pct,0.676768,0.58841
ft.pass_backward_pct,0.319865,0.40416
ft.pass_forward_completion_pct,0.626866,0.825758
ft.pass_backward_completion_pct,0.905263,0.948529
ft.pass_left_pct,0.461279,0.468053
ft.pass_right_pct,0.535354,0.527489
ft.pass_left_completion_pct,0.729927,0.869841
ft.pass_right_completion_pct,0.710692,0.878873
ft.pass_defensive_third_pct,0.329966,0.218425
ft.pass_mid_third_pct,0.346801,0.433878
ft.pass_final_third_pct,0.323232,0.347697
ft.pass_defensive_third_completion_pct,0.918367,0.959184
ft.pass_mid_third_completion_pct,0.631068,0.910959
ft.pass_final_third_completion_pct,0.604167,0.777778
ft.dribble_success_pct,0.5,0.26087
ft.tackle_success_pct,0.413793,0.416667
ft.aerial_duel_win_pct,0.578947,0.421053
ft.loss_possession_dispossessed_pct,0.291667,0.423077
ft.loss_possession_turnover_pct,0.708333,0.576923

--------------------------------------------------------------------------------

In [ ]:
# # season = config.get("season").get("year")
# db[mongo_config.get('collection').get("collection_processed_events")].delete_many({})
# db[mongo_config.get('collection').get("collection_team_game_stats")].delete_many({})
# db[mongo_config.get('collection').get("collection_player_game_stats")].delete_many({})

In [ ]:
# games = pd.DataFrame(db[mongo_config.get('collection').get("collection_raw_events")].find({'season': season}))

In [ ]:
# games.groupby('week')['game_id'].nunique()