In [17]:
from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Optional, Set

import numpy as np
import pandas as pd
from pymongo import MongoClient
import yaml

In [18]:
def load_config(path: str | Path = "../config/config.yaml") -> dict[str, Any]:
    path = Path(path)
    if not path.exists():
        path = Path("config/config.yaml")
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


config = load_config()
mongo_config = config["mongo"]

In [19]:
client = MongoClient(mongo_config.get('url'))
db = client[mongo_config.get('db')]
col_schedule = db[mongo_config.get('collection').get('collection_schedule')]
season = '2009-2010'
df_schedule = pd.DataFrame(col_schedule.find({'season': season}))
check_games = df_schedule['game_id'].sample(5, random_state=1909).values.tolist()

In [20]:
col_team_stats = db[mongo_config.get('collection').get('collection_team_game_stats')]
col_player_stats = db[mongo_config.get('collection').get('collection_player_game_stats')]

df_team_stats = pd.DataFrame(col_team_stats.find({'game_id': {"$in": check_games}}))
df_player_stast = pd.DataFrame(col_player_stats.find({'game_id': {"$in": check_games}}))

In [21]:
pd.set_option("display.max_rows", None)

for game in check_games:
    team_stats = df_team_stats[df_team_stats.game_id == game]
    team_stats = team_stats.sort_values(by='game_venue', ascending=False).reset_index(drop=True)
    game_info = team_stats[['game_id', 'game_date', 'week', 'team_name', 'game_venue']]
    stats = pd.json_normalize(team_stats.stats)
    stats_df = stats[[col for col in stats.columns if 'ft.' in col]]
    
    final_game = pd.merge(
        game_info,
        stats_df,
        left_index=True,
        right_index=True
    )
    display(final_game.T)
    print("\n" + "-" * 80 + "\n")

,0,1
game_id,328154,328154
game_date,2009-12-19 14:30:00,2009-12-19 14:30:00
week,17,17
team_name,Eintracht Frankfurt,Wolfsburg
game_venue,home,away
ft.possession,0.517602,0.482398
ft.goals,2,2
ft.shots,12,13
ft.shot_goal,2,2
ft.shot_on_target,4,5
ft.shot_off_target,4,5
ft.shot_woodwork,0,0
ft.shot_blocked,4,3
ft.shot_own_goal,0,0
ft.shot_zone_6_yard_box,0,1
ft.shot_zone_penalty_area,4,9
ft.shot_zone_outside_box,8,3
ft.shot_open_play,9,8
ft.shot_fastbreak,1,3
ft.shot_set_piece,1,0
ft.shot_penalty,0,0
ft.shot_right_foot,6,6
ft.shot_left_foot,4,5
ft.shot_head,2,2
ft.shot_other_body_part,0,0
ft.pass_attempt,544,507
ft.pass_completed,436,406
ft.pass_cross,23,17
ft.pass_freekick,17,12
ft.pass_corner,5,3
ft.pass_through_ball,2,8
ft.pass_throw_in,13,26
ft.pass_key_pass,7,11
ft.pass_assist,1,1
ft.pass_long,63,47
ft.pass_short,481,460
ft.pass_chipped,52,47
ft.pass_ground,492,460
ft.pass_head,39,30
ft.pass_feet,505,477
ft.pass_forward,376,334
ft.pass_backward,164,172
ft.pass_left,273,246
ft.pass_right,270,259
ft.pass_defensive_third,90,91
ft.pass_mid_third,285,277
ft.pass_final_third,169,139
ft.dribbles,6,7
ft.dribble_successful,2,0
ft.dribble_unsuccessful,4,7
ft.tackles_attempted,18,19
ft.tackle_gained_possession,9,14
ft.tackle_did_not_get_possession,9,3
ft.tackle_was_dribbled,0,2
ft.interceptions,21,23
ft.clearances,18,28
ft.clearance_head,6,9
ft.clearance_feet,12,19
ft.blocks,5,8
ft.blocked_shot,3,4
ft.blocked_cross,2,4
ft.offsides,3,6
ft.foul_committed,16,22
ft.foul_suffered,22,16
ft.aerial_duels,9,9
ft.aerial_duel_won,5,4
ft.aerial_duel_lost,4,5
ft.touches,667,641
ft.loss_of_possession,13,11
ft.dispossessed,13,11
ft.turnover,0,0
ft.errors,0,0
ft.error_leading_to_shot,0,0
ft.error_leading_to_goal,0,0
ft.goalkeeper_actions,6,19
ft.saves,3,2
ft.claims,0,6
ft.punches,0,0
ft.keeper_pickup,3,10
ft.keeper_sweeper,0,1
ft.ball_recoveries,60,44
ft.cards,1,1
ft.yellow_card,1,1
ft.second_yellow_card,0,0
ft.red_card,0,0
ft.pass_cross_completed,5,7
ft.pass_long_completed,40,26
ft.pass_short_completed,396,380
ft.pass_chipped_completed,23,22
ft.pass_ground_completed,413,384
ft.pass_head_completed,22,20
ft.pass_feet_completed,414,386
ft.pass_forward_completed,283,238
ft.pass_backward_completed,151,167
ft.pass_left_completed,215,195
ft.pass_right_completed,221,210
ft.pass_defensive_third_completed,83,88
ft.pass_mid_third_completed,250,238
ft.pass_final_third_completed,103,80
ft.shot_zone_inside_box,4,10
ft.shot_foot,10,11
ft.shot_accuracy,0.333333,0.384615
ft.goal_conversion_pct,0.166667,0.153846
ft.shot_on_target_conversion_pct,0.5,0.4
ft.shot_blocked_pct,0.333333,0.230769
ft.shot_outside_box_pct,0.666667,0.230769
ft.shot_inside_box_pct,0.333333,0.769231
ft.shot_6_yard_box_pct,0.0,0.076923
ft.shot_penalty_area_pct,0.333333,0.692308
ft.shot_open_play_pct,0.75,0.615385
ft.shot_fastbreak_pct,0.083333,0.230769
ft.shot_set_piece_pct,0.083333,0.0
ft.shot_penalty_pct,0.0,0.0
ft.shot_foot_pct,0.833333,0.846154
ft.shot_right_foot_pct,0.6,0.545455
ft.shot_left_foot_pct,0.4,0.454545
ft.shot_head_pct,0.166667,0.153846
ft.shot_other_body_part_pct,0.0,0.0
ft.pass_completion_pct,0.801471,0.800789
ft.pass_cross_completion_pct,0.217391,0.411765
ft.pass_long_pct,0.115809,0.092702
ft.pass_short_pct,0.884191,0.907298
ft.pass_long_completion_pct,0.634921,0.553191
ft.pass_short_completion_pct,0.823285,0.826087
ft.pass_chipped_pct,0.095588,0.092702
ft.pass_ground_pct,0.904412,0.907298
ft.pass_chipped_completion_pct,0.442308,0.468085
ft.pass_ground_completion_pct,0.839431,0.834783
ft.pass_head_pct,0.071691,0.059172
ft.pass_feet_pct,0.928309,0.940828
ft.pass_head_completion_pct,0.564103,0.666667
ft.pass_feet_completion_pct,0.819802,0.809224
ft.pass_forward_pct,0.691176,0.658777
ft.pass_backward_pct,0.301471,0.33925
ft.pass_forward_completion_pct,0.75266,0.712575
ft.pass_backward_completion_pct,0.920732,0.97093
ft.pass_left_pct,0.501838,0.485207
ft.pass_right_pct,0.496324,0.510848
ft.pass_left_completion_pct,0.787546,0.792683
ft.pass_right_completion_pct,0.818519,0.810811
ft.pass_defensive_third_pct,0.165441,0.179487
ft.pass_mid_third_pct,0.523897,0.546351
ft.pass_final_third_pct,0.310662,0.274162
ft.pass_defensive_third_completion_pct,0.922222,0.967033
ft.pass_mid_third_completion_pct,0.877193,0.859206
ft.pass_final_third_completion_pct,0.609467,0.57554
ft.dribble_success_pct,0.333333,0.0
ft.tackle_success_pct,0.5,0.736842
ft.aerial_duel_win_pct,0.555556,0.444444
ft.loss_possession_dispossessed_pct,1.0,1.0
ft.loss_possession_turnover_pct,0.0,0.0

--------------------------------------------------------------------------------

,0,1
game_id,328236,328236
game_date,2010-03-13 14:30:00,2010-03-13 14:30:00
week,26,26
team_name,Bochum,Borussia Dortmund
game_venue,home,away
ft.possession,0.392665,0.607335
ft.goals,1,4
ft.shots,11,13
ft.shot_goal,1,4
ft.shot_on_target,2,9
ft.shot_off_target,5,3
ft.shot_woodwork,0,1
ft.shot_blocked,4,1
ft.shot_own_goal,0,0
ft.shot_zone_6_yard_box,1,1
ft.shot_zone_penalty_area,5,7
ft.shot_zone_outside_box,5,5
ft.shot_open_play,9,10
ft.shot_fastbreak,0,0
ft.shot_set_piece,0,1
ft.shot_penalty,0,0
ft.shot_right_foot,8,8
ft.shot_left_foot,2,3
ft.shot_head,1,1
ft.shot_other_body_part,0,1
ft.pass_attempt,439,679
ft.pass_completed,312,556
ft.pass_cross,15,16
ft.pass_freekick,9,6
ft.pass_corner,3,4
ft.pass_through_ball,1,6
ft.pass_throw_in,35,12
ft.pass_key_pass,9,8
ft.pass_assist,1,2
ft.pass_long,78,52
ft.pass_short,361,627
ft.pass_chipped,66,32
ft.pass_ground,373,647
ft.pass_head,39,55
ft.pass_feet,400,624
ft.pass_forward,321,472
ft.pass_backward,116,204
ft.pass_left,208,348
ft.pass_right,226,328
ft.pass_defensive_third,77,86
ft.pass_mid_third,238,423
ft.pass_final_third,124,170
ft.dribbles,18,16
ft.dribble_successful,11,9
ft.dribble_unsuccessful,7,7
ft.tackles_attempted,36,32
ft.tackle_gained_possession,22,19
ft.tackle_did_not_get_possession,5,2
ft.tackle_was_dribbled,9,11
ft.interceptions,17,41
ft.clearances,18,17
ft.clearance_head,7,3
ft.clearance_feet,11,14
ft.blocks,1,6
ft.blocked_shot,1,4
ft.blocked_cross,0,2
ft.offsides,1,3
ft.foul_committed,7,11
ft.foul_suffered,11,7
ft.aerial_duels,6,6
ft.aerial_duel_won,2,4
ft.aerial_duel_lost,4,2
ft.touches,555,846
ft.loss_of_possession,14,20
ft.dispossessed,14,20
ft.turnover,0,0
ft.errors,1,0
ft.error_leading_to_shot,0,0
ft.error_leading_to_goal,1,0
ft.goalkeeper_actions,24,3
ft.saves,5,1
ft.claims,1,0
ft.punches,2,0
ft.keeper_pickup,15,1
ft.keeper_sweeper,1,1
ft.ball_recoveries,49,71
ft.cards,1,2
ft.yellow_card,0,2
ft.second_yellow_card,0,0
ft.red_card,1,0
ft.pass_cross_completed,6,7
ft.pass_long_completed,44,30
ft.pass_short_completed,268,526
ft.pass_chipped_completed,29,17
ft.pass_ground_completed,283,539
ft.pass_head_completed,21,32
ft.pass_feet_completed,291,524
ft.pass_forward_completed,206,364
ft.pass_backward_completed,104,190
ft.pass_left_completed,140,276
ft.pass_right_completed,172,277
ft.pass_defensive_third_completed,69,81
ft.pass_mid_third_completed,177,368
ft.pass_final_third_completed,66,107
ft.shot_zone_inside_box,6,8
ft.shot_foot,10,11
ft.shot_accuracy,0.181818,0.692308
ft.goal_conversion_pct,0.090909,0.307692
ft.shot_on_target_conversion_pct,0.5,0.444444
ft.shot_blocked_pct,0.363636,0.076923
ft.shot_outside_box_pct,0.454545,0.384615
ft.shot_inside_box_pct,0.545455,0.615385
ft.shot_6_yard_box_pct,0.090909,0.076923
ft.shot_penalty_area_pct,0.454545,0.538462
ft.shot_open_play_pct,0.818182,0.769231
ft.shot_fastbreak_pct,0.0,0.0
ft.shot_set_piece_pct,0.0,0.076923
ft.shot_penalty_pct,0.0,0.0
ft.shot_foot_pct,0.909091,0.846154
ft.shot_right_foot_pct,0.8,0.727273
ft.shot_left_foot_pct,0.2,0.272727
ft.shot_head_pct,0.090909,0.076923
ft.shot_other_body_part_pct,0.0,0.076923
ft.pass_completion_pct,0.710706,0.818851
ft.pass_cross_completion_pct,0.4,0.4375
ft.pass_long_pct,0.177677,0.076583
ft.pass_short_pct,0.822323,0.923417
ft.pass_long_completion_pct,0.564103,0.576923
ft.pass_short_completion_pct,0.742382,0.838915
ft.pass_chipped_pct,0.150342,0.047128
ft.pass_ground_pct,0.849658,0.952872
ft.pass_chipped_completion_pct,0.439394,0.53125
ft.pass_ground_completion_pct,0.758713,0.833076
ft.pass_head_pct,0.088838,0.081001
ft.pass_feet_pct,0.911162,0.918999
ft.pass_head_completion_pct,0.538462,0.581818
ft.pass_feet_completion_pct,0.7275,0.839744
ft.pass_forward_pct,0.731207,0.69514
ft.pass_backward_pct,0.264237,0.300442
ft.pass_forward_completion_pct,0.641745,0.771186
ft.pass_backward_completion_pct,0.896552,0.931373
ft.pass_left_pct,0.473804,0.512518
ft.pass_right_pct,0.514806,0.483063
ft.pass_left_completion_pct,0.673077,0.793103
ft.pass_right_completion_pct,0.761062,0.844512
ft.pass_defensive_third_pct,0.175399,0.126657
ft.pass_mid_third_pct,0.542141,0.622975
ft.pass_final_third_pct,0.28246,0.250368
ft.pass_defensive_third_completion_pct,0.896104,0.94186
ft.pass_mid_third_completion_pct,0.743697,0.869976
ft.pass_final_third_completion_pct,0.532258,0.629412
ft.dribble_success_pct,0.611111,0.5625
ft.tackle_success_pct,0.611111,0.59375
ft.aerial_duel_win_pct,0.333333,0.666667
ft.loss_possession_dispossessed_pct,1.0,1.0
ft.loss_possession_turnover_pct,0.0,0.0

--------------------------------------------------------------------------------

,0,1
game_id,328189,328189
game_date,2010-02-06 14:30:00,2010-02-06 14:30:00
week,21,21
team_name,FC Koln,Hamburger SV
game_venue,home,away
ft.possession,0.465863,0.534137
ft.goals,3,3
ft.shots,17,14
ft.shot_goal,3,3
ft.shot_on_target,8,9
ft.shot_off_target,6,5
ft.shot_woodwork,0,0
ft.shot_blocked,3,0
ft.shot_own_goal,0,0
ft.shot_zone_6_yard_box,2,1
ft.shot_zone_penalty_area,6,9
ft.shot_zone_outside_box,9,4
ft.shot_open_play,7,7
ft.shot_fastbreak,1,3
ft.shot_set_piece,6,1
ft.shot_penalty,0,1
ft.shot_right_foot,7,9
ft.shot_left_foot,7,4
ft.shot_head,3,1
ft.shot_other_body_part,0,0
ft.pass_attempt,348,399
ft.pass_completed,252,283
ft.pass_cross,15,14
ft.pass_freekick,18,15
ft.pass_corner,2,2
ft.pass_through_ball,6,5
ft.pass_throw_in,17,22
ft.pass_key_pass,12,10
ft.pass_assist,2,1
ft.pass_long,54,85
ft.pass_short,294,314
ft.pass_chipped,48,51
ft.pass_ground,300,348
ft.pass_head,32,33
ft.pass_feet,316,366
ft.pass_forward,261,265
ft.pass_backward,86,133
ft.pass_left,172,202
ft.pass_right,174,196
ft.pass_defensive_third,47,88
ft.pass_mid_third,190,179
ft.pass_final_third,111,132
ft.dribbles,28,22
ft.dribble_successful,17,8
ft.dribble_unsuccessful,11,14
ft.tackles_attempted,29,40
ft.tackle_gained_possession,18,17
ft.tackle_did_not_get_possession,3,6
ft.tackle_was_dribbled,8,17
ft.interceptions,12,15
ft.clearances,17,21
ft.clearance_head,10,11
ft.clearance_feet,7,10
ft.blocks,3,4
ft.blocked_shot,0,3
ft.blocked_cross,3,1
ft.offsides,8,2
ft.foul_committed,20,27
ft.foul_suffered,27,20
ft.aerial_duels,21,21
ft.aerial_duel_won,10,11
ft.aerial_duel_lost,11,10
ft.touches,496,519
ft.loss_of_possession,12,7
ft.dispossessed,12,7
ft.turnover,0,0
ft.errors,1,0
ft.error_leading_to_shot,0,0
ft.error_leading_to_goal,1,0
ft.goalkeeper_actions,12,8
ft.saves,6,5
ft.claims,0,0
ft.punches,0,0
ft.keeper_pickup,6,3
ft.keeper_sweeper,0,0
ft.ball_recoveries,50,44
ft.cards,2,2
ft.yellow_card,2,2
ft.second_yellow_card,0,0
ft.red_card,0,0
ft.pass_cross_completed,6,2
ft.pass_long_completed,32,41
ft.pass_short_completed,220,242
ft.pass_chipped_completed,24,20
ft.pass_ground_completed,228,263
ft.pass_head_completed,16,15
ft.pass_feet_completed,236,268
ft.pass_forward_completed,175,157
ft.pass_backward_completed,76,125
ft.pass_left_completed,133,147
ft.pass_right_completed,119,135
ft.pass_defensive_third_completed,42,79
ft.pass_mid_third_completed,153,135
ft.pass_final_third_completed,57,69
ft.shot_zone_inside_box,8,10
ft.shot_foot,14,13
ft.shot_accuracy,0.470588,0.642857
ft.goal_conversion_pct,0.176471,0.214286
ft.shot_on_target_conversion_pct,0.375,0.333333
ft.shot_blocked_pct,0.176471,0.0
ft.shot_outside_box_pct,0.529412,0.285714
ft.shot_inside_box_pct,0.470588,0.714286
ft.shot_6_yard_box_pct,0.117647,0.071429
ft.shot_penalty_area_pct,0.352941,0.642857
ft.shot_open_play_pct,0.411765,0.5
ft.shot_fastbreak_pct,0.058824,0.214286
ft.shot_set_piece_pct,0.352941,0.071429
ft.shot_penalty_pct,0.0,0.071429
ft.shot_foot_pct,0.823529,0.928571
ft.shot_right_foot_pct,0.5,0.692308
ft.shot_left_foot_pct,0.5,0.307692
ft.shot_head_pct,0.176471,0.071429
ft.shot_other_body_part_pct,0.0,0.0
ft.pass_completion_pct,0.724138,0.709273
ft.pass_cross_completion_pct,0.4,0.142857
ft.pass_long_pct,0.155172,0.213033
ft.pass_short_pct,0.844828,0.786967
ft.pass_long_completion_pct,0.592593,0.482353
ft.pass_short_completion_pct,0.748299,0.770701
ft.pass_chipped_pct,0.137931,0.12782
ft.pass_ground_pct,0.862069,0.87218
ft.pass_chipped_completion_pct,0.5,0.392157
ft.pass_ground_completion_pct,0.76,0.755747
ft.pass_head_pct,0.091954,0.082707
ft.pass_feet_pct,0.908046,0.917293
ft.pass_head_completion_pct,0.5,0.454545
ft.pass_feet_completion_pct,0.746835,0.73224
ft.pass_forward_pct,0.75,0.66416
ft.pass_backward_pct,0.247126,0.333333
ft.pass_forward_completion_pct,0.670498,0.592453
ft.pass_backward_completion_pct,0.883721,0.93985
ft.pass_left_pct,0.494253,0.506266
ft.pass_right_pct,0.5,0.491228
ft.pass_left_completion_pct,0.773256,0.727723
ft.pass_right_completion_pct,0.683908,0.688776
ft.pass_defensive_third_pct,0.135057,0.220551
ft.pass_mid_third_pct,0.545977,0.448622
ft.pass_final_third_pct,0.318966,0.330827
ft.pass_defensive_third_completion_pct,0.893617,0.897727
ft.pass_mid_third_completion_pct,0.805263,0.75419
ft.pass_final_third_completion_pct,0.513514,0.522727
ft.dribble_success_pct,0.607143,0.363636
ft.tackle_success_pct,0.62069,0.425
ft.aerial_duel_win_pct,0.47619,0.52381
ft.loss_possession_dispossessed_pct,1.0,1.0
ft.loss_possession_turnover_pct,0.0,0.0

--------------------------------------------------------------------------------

,0,1
game_id,328287,328287
game_date,2010-04-18 16:30:00,2010-04-18 16:30:00
week,31,31
team_name,Eintracht Frankfurt,Hertha Berlin
game_venue,home,away
ft.possession,0.492872,0.507128
ft.goals,2,2
ft.shots,10,10
ft.shot_goal,2,2
ft.shot_on_target,7,7
ft.shot_off_target,2,1
ft.shot_woodwork,1,0
ft.shot_blocked,1,2
ft.shot_own_goal,0,0
ft.shot_zone_6_yard_box,0,2
ft.shot_zone_penalty_area,6,6
ft.shot_zone_outside_box,4,2
ft.shot_open_play,7,9
ft.shot_fastbreak,0,1
ft.shot_set_piece,2,0
ft.shot_penalty,1,0
ft.shot_right_foot,7,6
ft.shot_left_foot,1,2
ft.shot_head,2,2
ft.shot_other_body_part,0,0
ft.pass_attempt,484,498
ft.pass_completed,359,359
ft.pass_cross,15,18
ft.pass_freekick,8,19
ft.pass_corner,3,4
ft.pass_through_ball,1,1
ft.pass_throw_in,18,26
ft.pass_key_pass,9,8
ft.pass_assist,2,1
ft.pass_long,66,85
ft.pass_short,418,413
ft.pass_chipped,76,73
ft.pass_ground,408,425
ft.pass_head,68,43
ft.pass_feet,416,455
ft.pass_forward,350,351
ft.pass_backward,134,144
ft.pass_left,234,239
ft.pass_right,246,258
ft.pass_defensive_third,67,55
ft.pass_mid_third,263,276
ft.pass_final_third,154,167
ft.dribbles,22,16
ft.dribble_successful,13,5
ft.dribble_unsuccessful,9,11
ft.tackles_attempted,29,35
ft.tackle_gained_possession,20,18
ft.tackle_did_not_get_possession,4,4
ft.tackle_was_dribbled,5,13
ft.interceptions,8,30
ft.clearances,17,16
ft.clearance_head,10,9
ft.clearance_feet,7,7
ft.blocks,6,0
ft.blocked_shot,2,0
ft.blocked_cross,4,0
ft.offsides,4,5
ft.foul_committed,22,10
ft.foul_suffered,10,22
ft.aerial_duels,17,17
ft.aerial_duel_won,11,6
ft.aerial_duel_lost,6,11
ft.touches,620,625
ft.loss_of_possession,13,14
ft.dispossessed,13,14
ft.turnover,0,0
ft.errors,0,0
ft.error_leading_to_shot,0,0
ft.error_leading_to_goal,0,0
ft.goalkeeper_actions,19,11
ft.saves,5,5
ft.claims,2,1
ft.punches,0,0
ft.keeper_pickup,11,4
ft.keeper_sweeper,1,1
ft.ball_recoveries,78,64
ft.cards,2,0
ft.yellow_card,2,0
ft.second_yellow_card,0,0
ft.red_card,0,0
ft.pass_cross_completed,1,2
ft.pass_long_completed,33,42
ft.pass_short_completed,326,317
ft.pass_chipped_completed,32,32
ft.pass_ground_completed,327,327
ft.pass_head_completed,39,17
ft.pass_feet_completed,320,342
ft.pass_forward_completed,237,229
ft.pass_backward_completed,122,128
ft.pass_left_completed,172,180
ft.pass_right_completed,184,178
ft.pass_defensive_third_completed,59,50
ft.pass_mid_third_completed,221,214
ft.pass_final_third_completed,79,95
ft.shot_zone_inside_box,6,8
ft.shot_foot,8,8
ft.shot_accuracy,0.7,0.7
ft.goal_conversion_pct,0.2,0.2
ft.shot_on_target_conversion_pct,0.285714,0.285714
ft.shot_blocked_pct,0.1,0.2
ft.shot_outside_box_pct,0.4,0.2
ft.shot_inside_box_pct,0.6,0.8
ft.shot_6_yard_box_pct,0.0,0.2
ft.shot_penalty_area_pct,0.6,0.6
ft.shot_open_play_pct,0.7,0.9
ft.shot_fastbreak_pct,0.0,0.1
ft.shot_set_piece_pct,0.2,0.0
ft.shot_penalty_pct,0.1,0.0
ft.shot_foot_pct,0.8,0.8
ft.shot_right_foot_pct,0.875,0.75
ft.shot_left_foot_pct,0.125,0.25
ft.shot_head_pct,0.2,0.2
ft.shot_other_body_part_pct,0.0,0.0
ft.pass_completion_pct,0.741736,0.720884
ft.pass_cross_completion_pct,0.066667,0.111111
ft.pass_long_pct,0.136364,0.170683
ft.pass_short_pct,0.863636,0.829317
ft.pass_long_completion_pct,0.5,0.494118
ft.pass_short_completion_pct,0.779904,0.767554
ft.pass_chipped_pct,0.157025,0.146586
ft.pass_ground_pct,0.842975,0.853414
ft.pass_chipped_completion_pct,0.421053,0.438356
ft.pass_ground_completion_pct,0.801471,0.769412
ft.pass_head_pct,0.140496,0.086345
ft.pass_feet_pct,0.859504,0.913655
ft.pass_head_completion_pct,0.573529,0.395349
ft.pass_feet_completion_pct,0.769231,0.751648
ft.pass_forward_pct,0.72314,0.704819
ft.pass_backward_pct,0.27686,0.289157
ft.pass_forward_completion_pct,0.677143,0.652422
ft.pass_backward_completion_pct,0.910448,0.888889
ft.pass_left_pct,0.483471,0.47992
ft.pass_right_pct,0.508264,0.518072
ft.pass_left_completion_pct,0.735043,0.753138
ft.pass_right_completion_pct,0.747967,0.689922
ft.pass_defensive_third_pct,0.13843,0.110442
ft.pass_mid_third_pct,0.543388,0.554217
ft.pass_final_third_pct,0.318182,0.335341
ft.pass_defensive_third_completion_pct,0.880597,0.909091
ft.pass_mid_third_completion_pct,0.840304,0.775362
ft.pass_final_third_completion_pct,0.512987,0.568862
ft.dribble_success_pct,0.590909,0.3125
ft.tackle_success_pct,0.689655,0.514286
ft.aerial_duel_win_pct,0.647059,0.352941
ft.loss_possession_dispossessed_pct,1.0,1.0
ft.loss_possession_turnover_pct,0.0,0.0

--------------------------------------------------------------------------------

,0,1
game_id,328251,328251
game_date,2010-03-27 14:30:00,2010-03-27 14:30:00
week,28,28
team_name,Bayern Munich,VfB Stuttgart
game_venue,home,away
ft.possession,0.569143,0.430857
ft.goals,1,2
ft.shots,9,15
ft.shot_goal,1,2
ft.shot_on_target,3,8
ft.shot_off_target,5,7
ft.shot_woodwork,0,0
ft.shot_blocked,1,0
ft.shot_own_goal,0,0
ft.shot_zone_6_yard_box,1,1
ft.shot_zone_penalty_area,3,6
ft.shot_zone_outside_box,5,8
ft.shot_open_play,8,7
ft.shot_fastbreak,0,2
ft.shot_set_piece,1,6
ft.shot_penalty,0,0
ft.shot_right_foot,5,9
ft.shot_left_foot,2,2
ft.shot_head,2,4
ft.shot_other_body_part,0,0
ft.pass_attempt,498,377
ft.pass_completed,374,278
ft.pass_cross,27,10
ft.pass_freekick,21,14
ft.pass_corner,4,2
ft.pass_through_ball,0,1
ft.pass_throw_in,23,19
ft.pass_key_pass,7,12
ft.pass_assist,1,1
ft.pass_long,96,73
ft.pass_short,402,304
ft.pass_chipped,53,52
ft.pass_ground,445,325
ft.pass_head,42,46
ft.pass_feet,456,331
ft.pass_forward,316,269
ft.pass_backward,160,107
ft.pass_left,248,194
ft.pass_right,229,182
ft.pass_defensive_third,89,66
ft.pass_mid_third,233,184
ft.pass_final_third,176,127
ft.dribbles,14,8
ft.dribble_successful,5,5
ft.dribble_unsuccessful,9,3
ft.tackles_attempted,18,22
ft.tackle_gained_possession,9,14
ft.tackle_did_not_get_possession,4,3
ft.tackle_was_dribbled,5,5
ft.interceptions,8,13
ft.clearances,5,16
ft.clearance_head,2,4
ft.clearance_feet,3,12
ft.blocks,2,7
ft.blocked_shot,0,1
ft.blocked_cross,2,6
ft.offsides,4,0
ft.foul_committed,16,23
ft.foul_suffered,23,16
ft.aerial_duels,12,12
ft.aerial_duel_won,7,5
ft.aerial_duel_lost,5,7
ft.touches,574,499
ft.loss_of_possession,8,10
ft.dispossessed,8,10
ft.turnover,0,0
ft.errors,0,0
ft.error_leading_to_shot,0,0
ft.error_leading_to_goal,0,0
ft.goalkeeper_actions,9,20
ft.saves,6,2
ft.claims,0,2
ft.punches,0,1
ft.keeper_pickup,3,15
ft.keeper_sweeper,0,0
ft.ball_recoveries,42,43
ft.cards,1,1
ft.yellow_card,1,1
ft.second_yellow_card,0,0
ft.red_card,0,0
ft.pass_cross_completed,6,6
ft.pass_long_completed,64,37
ft.pass_short_completed,310,241
ft.pass_chipped_completed,24,29
ft.pass_ground_completed,350,249
ft.pass_head_completed,13,26
ft.pass_feet_completed,361,252
ft.pass_forward_completed,223,184
ft.pass_backward_completed,148,93
ft.pass_left_completed,195,141
ft.pass_right_completed,177,136
ft.pass_defensive_third_completed,81,63
ft.pass_mid_third_completed,194,138
ft.pass_final_third_completed,99,77
ft.shot_zone_inside_box,4,7
ft.shot_foot,7,11
ft.shot_accuracy,0.333333,0.533333
ft.goal_conversion_pct,0.111111,0.133333
ft.shot_on_target_conversion_pct,0.333333,0.25
ft.shot_blocked_pct,0.111111,0.0
ft.shot_outside_box_pct,0.555556,0.533333
ft.shot_inside_box_pct,0.444444,0.466667
ft.shot_6_yard_box_pct,0.111111,0.066667
ft.shot_penalty_area_pct,0.333333,0.4
ft.shot_open_play_pct,0.888889,0.466667
ft.shot_fastbreak_pct,0.0,0.133333
ft.shot_set_piece_pct,0.111111,0.4
ft.shot_penalty_pct,0.0,0.0
ft.shot_foot_pct,0.777778,0.733333
ft.shot_right_foot_pct,0.714286,0.818182
ft.shot_left_foot_pct,0.285714,0.181818
ft.shot_head_pct,0.222222,0.266667
ft.shot_other_body_part_pct,0.0,0.0
ft.pass_completion_pct,0.751004,0.737401
ft.pass_cross_completion_pct,0.222222,0.6
ft.pass_long_pct,0.192771,0.193634
ft.pass_short_pct,0.807229,0.806366
ft.pass_long_completion_pct,0.666667,0.506849
ft.pass_short_completion_pct,0.771144,0.792763
ft.pass_chipped_pct,0.106426,0.137931
ft.pass_ground_pct,0.893574,0.862069
ft.pass_chipped_completion_pct,0.45283,0.557692
ft.pass_ground_completion_pct,0.786517,0.766154
ft.pass_head_pct,0.084337,0.122016
ft.pass_feet_pct,0.915663,0.877984
ft.pass_head_completion_pct,0.309524,0.565217
ft.pass_feet_completion_pct,0.791667,0.761329
ft.pass_forward_pct,0.634538,0.713528
ft.pass_backward_pct,0.321285,0.28382
ft.pass_forward_completion_pct,0.705696,0.684015
ft.pass_backward_completion_pct,0.925,0.869159
ft.pass_left_pct,0.497992,0.514589
ft.pass_right_pct,0.459839,0.482759
ft.pass_left_completion_pct,0.78629,0.726804
ft.pass_right_completion_pct,0.772926,0.747253
ft.pass_defensive_third_pct,0.178715,0.175066
ft.pass_mid_third_pct,0.467871,0.488064
ft.pass_final_third_pct,0.353414,0.33687
ft.pass_defensive_third_completion_pct,0.910112,0.954545
ft.pass_mid_third_completion_pct,0.832618,0.75
ft.pass_final_third_completion_pct,0.5625,0.606299
ft.dribble_success_pct,0.357143,0.625
ft.tackle_success_pct,0.5,0.636364
ft.aerial_duel_win_pct,0.583333,0.416667
ft.loss_possession_dispossessed_pct,1.0,1.0
ft.loss_possession_turnover_pct,0.0,0.0

--------------------------------------------------------------------------------

In [22]:
mongo_config

{'backup_folder': './mongo_backup',
 'db': 'WhoScored',
 'url': 'mongodb://localhost:27017/',
 'collection': {'collection_teams': 'available_teams',
  'collection_schedule': 'game_schedule',
  'collection_logs': 'error_logs',
  'collection_raw_events': 'game_raw_events',
  'collection_processed_events': 'game_processed_events',
  'collection_team_game_stats': 'game_team_stats',
  'collection_player_game_stats': 'game_player_stats'}}

In [ ]:
# db[mongo_config.get('collection').get("collection_schedule")].delete_many({})
# db[mongo_config.get('collection').get("collection_raw_events")].delete_many({})
# db[mongo_config.get('collection').get("collection_processed_events")].delete_many({})
# db[mongo_config.get('collection').get("collection_team_game_stats")].delete_many({})
# db[mongo_config.get('collection').get("collection_player_game_stats")].delete_many({})

In [29]:
game = pd.DataFrame(db[mongo_config.get('collection').get("collection_raw_events")].find({"game_id": 328154}))

In [34]:
game[game.is_goal == True]

,_id,game_id,away_team_id,away_team_name,competition_country,competition_name,game_date,game_status,home_team_id,home_team_name,...,blocked_x,blocked_y,qualifiers,is_touch,is_shot,is_goal,card_type,related_event_id,related_player_id,event_idx
502,6a09bef5f73bd6958dd7d45f,328154,33,Wolfsburg,Germany,Bundesliga,2009-12-19 14:30:00,finished,45,Eintracht Frankfurt,...,NaN,NaN,"[{'type': {'displayName': 'BoxCentre', 'value'...",True,True,True,NaN,293.0,6268.0,502
671,6a09bef5f73bd6958dd7d508,328154,33,Wolfsburg,Germany,Bundesliga,2009-12-19 14:30:00,finished,45,Eintracht Frankfurt,...,NaN,NaN,"[{'type': {'displayName': 'GoalMouthY', 'value...",True,True,True,NaN,346.0,11269.0,671
1233,6a09bef5f73bd6958dd7d73a,328154,33,Wolfsburg,Germany,Bundesliga,2009-12-19 14:30:00,finished,45,Eintracht Frankfurt,...,NaN,NaN,"[{'type': {'displayName': 'GoalMouthY', 'value...",True,True,True,NaN,NaN,NaN,1233
1383,6a09bef5f73bd6958dd7d7d0,328154,33,Wolfsburg,Germany,Bundesliga,2009-12-19 14:30:00,finished,45,Eintracht Frankfurt,...,NaN,NaN,"[{'type': {'displayName': 'OutOfBoxCentre', 'v...",True,True,True,NaN,751.0,12392.0,1383

In [35]:
game[game.is_goal == True]['qualifiers'].values

array([list([{'type': {'displayName': 'BoxCentre', 'value': 17}}, {'type': {'displayName': 'Head', 'value': 15}}, {'type': {'displayName': 'Assisted', 'value': 29}}, {'type': {'displayName': 'GoalMouthZ', 'value': 103}, 'value': '12.5'}, {'type': {'displayName': 'Zone', 'value': 56}, 'value': 'Center'}, {'type': {'displayName': 'LowRight', 'value': 80}}, {'type': {'displayName': 'RelatedEventId', 'value': 55}, 'value': '293'}, {'type': {'displayName': 'SetPiece', 'value': 24}}, {'type': {'displayName': 'GoalMouthY', 'value': 102}, 'value': '46.7'}, {'type': {'displayName': 'IntentionalAssist', 'value': 154}}]),
       list([{'type': {'displayName': 'GoalMouthY', 'value': 102}, 'value': '50.9'}, {'type': {'displayName': 'GoalMouthZ', 'value': 103}, 'value': '2.8'}, {'type': {'displayName': 'Assisted', 'value': 29}}, {'type': {'displayName': 'BoxCentre', 'value': 17}}, {'type': {'displayName': 'Zone', 'value': 56}, 'value': 'Center'}, {'type': {'displayName': 'IntentionalAssist', 'value': 154}}, {'type': {'displayName': 'RelatedEventId', 'value': 55}, 'value': '346'}, {'type': {'displayName': 'FastBreak', 'value': 23}}, {'type': {'displayName': 'RightFoot', 'value': 20}}, {'type': {'displayName': 'LowCentre', 'value': 78}}]),
       list([{'type': {'displayName': 'GoalMouthY', 'value': 102}, 'value': '46.9'}, {'type': {'displayName': 'LowRight', 'value': 80}}, {'type': {'displayName': 'LeftFoot', 'value': 72}}, {'type': {'displayName': 'RegularPlay', 'value': 22}}, {'type': {'displayName': 'Zone', 'value': 56}, 'value': 'Center'}, {'type': {'displayName': 'BoxCentre', 'value': 17}}, {'type': {'displayName': 'GoalMouthZ', 'value': 103}, 'value': '16.7'}]),
       list([{'type': {'displayName': 'OutOfBoxCentre', 'value': 18}}, {'type': {'displayName': 'GoalMouthZ', 'value': 103}, 'value': '9.7'}, {'type': {'displayName': 'LowLeft', 'value': 76}}, {'type': {'displayName': 'RelatedEventId', 'value': 55}, 'value': '751'}, {'type': {'displayName': 'Assisted', 'value': 29}}, {'type': {'displayName': 'GoalMouthY', 'value': 102}, 'value': '53.8'}, {'type': {'displayName': 'Zone', 'value': 56}, 'value': 'Center'}, {'type': {'displayName': 'LeftFoot', 'value': 72}}, {'type': {'displayName': 'RegularPlay', 'value': 22}}])],
      dtype=object)