In [1]:
from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Optional, Set

import numpy as np
import pandas as pd
from pymongo import MongoClient
import yaml

from mplsoccer import Pitch
import matplotlib.pyplot as plt
from mplsoccer import VerticalPitch

In [2]:
def load_config(path: str | Path = "../config/config.yaml") -> dict[str, Any]:
    path = Path(path)
    if not path.exists():
        path = Path("config/config.yaml")
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


config = load_config()
mongo_config = config["mongo"]

In [3]:
client = MongoClient(mongo_config.get('url'))
db = client[mongo_config.get('db')]

In [4]:
shot_events = pd.DataFrame(list(db[mongo_config.get('collection').get('collection_processed_events')].find({'shot_event': True})))

In [16]:
def shot_statistics(df: pd.DataFrame, stat: str) -> pd.Series:

    counts_value = df[stat].value_counts().reset_index(drop=False)
    counts_normalized = df[stat].value_counts(normalize=True).reset_index(drop=False)
    counts_stats = pd.merge(
        left=counts_value,
        right=counts_normalized,
        left_on=stat, right_on=stat
    )
    return counts_stats

In [17]:
shot_statistics(shot_events, 'shot_result')

  shot_result  count  proportion
0  Off Target  54775    0.403454
1     Blocked  32854    0.241992
2   On Target  32462    0.239104
3        Goal  15281    0.112555
4    Own Goal    393    0.002895

In [18]:
shot_statistics(shot_events, 'shot_situation')

  shot_situation  count  proportion
0      Open Play  87653    0.645623
1     Set Pieces  30940    0.227894
2        Unknown   8093    0.059610
3      Fastbreak   7195    0.052996
4        Penalty   1491    0.010982
5       Own Goal    393    0.002895

In [22]:
shot_statistics(shot_events, 'shot_zone')

        shot_zone  count  proportion
0    Penalty Area  74408    0.548065
1  Outside of box  51532    0.379568
2      6-yard box   9825    0.072368

In [24]:
shot_statistics(shot_events, 'shot_body_part')

     shot_body_part  count  proportion
0        Right foot  69468    0.511678
1         Left foot  41469    0.305447
2              Head  24344    0.179310
3  Other body parts    484    0.003565

In [29]:
shot_events[shot_events['shot_situation'] == 'Unknown'][['game_id','game_date','season','week','home_team_name','away_team_name','shot_result', 'shot_situation', 'shot_zone', 'shot_body_part']]

,game_id,game_date,season,week,home_team_name,away_team_name,shot_result,shot_situation,shot_zone,shot_body_part
4,327995,2009-08-07 19:30:00,2009-2010,1,Wolfsburg,VfB Stuttgart,Off Target,Unknown,Outside of box,Left foot
16,327995,2009-08-07 19:30:00,2009-2010,1,Wolfsburg,VfB Stuttgart,Off Target,Unknown,Outside of box,Left foot
19,327995,2009-08-07 19:30:00,2009-2010,1,Wolfsburg,VfB Stuttgart,Goal,Unknown,Outside of box,Left foot
20,327995,2009-08-07 19:30:00,2009-2010,1,Wolfsburg,VfB Stuttgart,Blocked,Unknown,6-yard box,Head
29,327997,2009-08-08 14:30:00,2009-2010,1,Borussia Dortmund,FC Koln,On Target,Unknown,6-yard box,Head
...,...,...,...,...,...,...,...,...,...,...
40041,724046,2014-03-29 14:30:00,2013-2014,28,VfB Stuttgart,Borussia Dortmund,Off Target,Unknown,Penalty Area,Head
40044,724046,2014-03-29 14:30:00,2013-2014,28,VfB Stuttgart,Borussia Dortmund,Off Target,Unknown,Penalty Area,Right foot
40045,724046,2014-03-29 14:30:00,2013-2014,28,VfB Stuttgart,Borussia Dortmund,Blocked,Unknown,Penalty Area,Left foot
40051,724046,2014-03-29 14:30:00,2013-2014,28,VfB Stuttgart,Borussia Dortmund,Off Target,Unknown,Outside of box,Right foot
40052,724046,2014-03-29 14:30:00,2013-2014,28,VfB Stuttgart,Borussia Dortmund,Off Target,Unknown,Penalty Area,Head

In [30]:
shot_events[shot_events['shot_situation'] == 'Unknown']['game_id'].value_counts()

game_id
420871    17
724033    17
621276    16
621286    15
621392    14
          ..
723811     1
723831     1
723918     1
723943     1
723945     1
Name: count, Length: 1447, dtype: int64

In [32]:
pd.set_option('display.max_columns', None)
shot_events[(shot_events['shot_situation'] == 'Unknown') & (shot_events['game_id'] == 420871)]

,_id,game_id,season,competition_country,competition_name,game_date,game_status,week,home_team_id,home_team_name,away_team_id,away_team_name,event_idx,period,minute,second,expanded_minute,team_id,team,player_id,player,type,outcome_type,x,y,end_x,end_y,goal_mouth_y,goal_mouth_z,blocked_x,blocked_y,related_event_id,related_player_id,stat_event_type,shot_event,pass_event,pass_completed,dribble_event,tackle_attempted_event,interception_event,clearance_event,block_event,offside_event,foul_event,aerial_duel_event,touch_event,loss_possession_event,error_event,save_event,claim_event,punch_event,goalkeeper_event,ball_recovery_event,card_event,substitution_event,shot_goal,shot_on_target,shot_off_target,shot_woodwork,shot_blocked,shot_own_goal,goal_assist,shot_zone_6_yard_box,shot_zone_penalty_area,shot_zone_outside_box,shot_open_play,shot_fastbreak,shot_set_piece,shot_penalty,shot_right_foot,shot_left_foot,shot_head,shot_other_body_part,shot_result,shot_zone,shot_situation,shot_body_part,pass_attempt,pass_incomplete,pass_cross,pass_freekick,pass_corner,pass_through_ball,pass_throw_in,pass_key_pass,pass_key_pass_qualifier,pass_long,pass_short,pass_length,pass_chipped,pass_ground,pass_height,pass_head,pass_feet,pass_body_part,pass_forward,pass_backward,pass_left,pass_right,pass_defensive_third,pass_mid_third,pass_final_third,pass_target_zone,dribble_successful,dribble_unsuccessful,tackle_gained_possession,tackle_did_not_get_possession,tackle_was_dribbled,tackle_result,clearance_head,clearance_feet,clearance_body_part,blocked_shot,blocked_cross,block_type,caught_offside,offside_pass,offside_provoked,offside_type,foul_committed,foul_suffered,foul_type,aerial_duel_won,aerial_duel_lost,aerial_result,dispossessed,turnover,loss_possession_type,error_leading_to_shot,error_leading_to_goal,error_type,keeper_pickup,keeper_sweeper,gk_type,yellow_card,second_yellow_card,red_card,card_type,substitution_on,substitution_off,substitution_type
10701,6a0ca079279178a2ca3eeb22,420871,2010-2011,Germany,Bundesliga,2010-11-13 14:30:00,finished,12,282,FC Koln,134,Borussia M.Gladbach,177,FirstHalf,10,42.0,10,134,Borussia M.Gladbach,41330.0,Marco Reus,MissedShots,Successful,87.2,42.7,None,None,42.4,4.2,NaN,NaN,NaN,NaN,shot,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,Off Target,Penalty Area,Unknown,Right foot,False,False,False,False,False,False,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,False,False,False,False,None,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None
10703,6a0ca079279178a2ca3eeb4b,420871,2010-2011,Germany,Bundesliga,2010-11-13 14:30:00,finished,12,282,FC Koln,134,Borussia M.Gladbach,218,FirstHalf,13,56.0,13,134,Borussia M.Gladbach,22825.0,Michael Bradley,MissedShots,Successful,70.8,58.4,None,None,42.0,65.3,NaN,NaN,NaN,NaN,shot,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,Off Target,Outside of box,Unknown,Right foot,False,False,False,False,False,False,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,False,False,False,False,None,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None
10707,6a0ca079279178a2ca3eebe5,420871,2010-2011,Germany,Bundesliga,2010-11-13 14:30:00,finished,12,282,FC Koln,134,Borussia M.Gladbach,372,FirstHalf,23,42.0,23,282,FC Koln,19279.0,Milivoje Novakovic,SavedShot,Successful,79.2,74.6,None,None,NaN,NaN,89.4,61.0,NaN,NaN,shot,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False,False,False,Blocked,Outside of box,Unknown,Right foot,False,False,False,False,False,False,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,False,False,False,False,None,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None
10711,6a0ca079279178a2ca3eec99,420871,2010-2011,Germany,Bundesliga,2010-11-13 14:30:00,finished,12,282,FC Koln,134,Borussia M.Gladbach,558,FirstHalf,35,53.0,35,134,Borussia M.Gladbach,3062.0,Thorben Marx,MissedShots,Successful,81.6,74.1,None,None,56.9,11.1,NaN,NaN,282.0,22825.0,shot,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,Off Target,Outside of box,Unknown,Right foot,False,False,False,False,False,False,False,True,False,False,False,None,False,False,None,False,False,None,False,False,False,False,False,False,False,None,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None
10712,6a0ca079279178a2ca3eec9d,420871,2010-2011,Germany,Bundesliga,2010-11-13 14:30:00,finished,12,282,FC Koln,134,Borussia M.Gladbach,565,FirstHalf,36,28.0,36,134,Borussia M.Gladbach,7367.0,Igor de Camargo,SavedShot,Successful,85.3,50.3,None,None,NaN,NaN,90.4,49.6,NaN,NaN,shot,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,True,False,False,False,Blocked,Penalty Area,Unknown,Right foot,False,False,False,False,False,False,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,False,False,False,False,None,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None
10713,6a0ca079279178a2ca3eec9f,420871,2010-2011,Germany,Bundesliga,2010-11-13 14:30:00,finished,12,282,FC Koln,134,Borussia M.Gladbach,567,FirstHalf,36,30.0,36,134,Borussia M.Gladbach,83234.0,Patrick Herrmann,SavedShot,Successful,80.9,31.9,None,None,NaN,NaN,88.1,41.7,NaN,NaN,shot,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False,False,False,Blocked,Outside of box,Unknown,Right foot,False,False,False,False,False,False,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,False,False,False,False,None,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None
10714,6a0ca079279178a2ca3eeca1,420871,2010-2011,Germany,Bundesliga,2010-11-13 14:30:00,finished,12,282,FC Koln,134,Borussia M.Gladbach,569,FirstHalf,36,33.0,36,134,Borussia M.Gladbach,3062.0,Thorben Marx,SavedShot,Successful,75.2,42.1,None,None,NaN,NaN,77.3,42.6,NaN,NaN,shot,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False,False,False,Blocked,Outside of box,Unknown,Right foot,False,False,False,False,False,False,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,False,False,False,False,None,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None
10715,6a0ca079279178a2ca3eecaa,420871,2010-2011,Germany,Bundesliga,2010-11-13 14:30:00,finished,12,282,FC Koln,134,Borussia M.Gladbach,580,FirstHalf,37,15.0,37,134,Borussia M.Gladbach,7367.0,Igor de Camargo,SavedShot,Successful,86.2,44.3,None,None,NaN,NaN,88.1,44.4,NaN,NaN,shot,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,True,False,False,False,Blocked,Penalty Area,Unknown,Right foot,False,False,False,False,False,False,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,False,False,False,False,None,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None
10717,6a0ca079279178a2ca3eece7,420871,2010-2011,Germany,Bundesliga,2010-11-13 14:30:00,finished,12,282,FC Koln,134,Borussia M.Gladbach,641,FirstHalf,40,11.0,40,282,FC Koln,19279.0,Milivoje Novakovic,MissedShots,Successful,75.9,71.7,None,None,58.5,50.0,NaN,NaN,NaN,NaN,shot,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,Off Target,Outside of box,Unknown,Right foot,False,False,False,False,False,False,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,False,False,False,False,None,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None
10720,6a0ca079279178a2ca3eed79,420871,2010-2011,Germany,Bundesliga,2010-11-13 14:30:00,finished,12,282,FC Koln,134,Borussia M.Gladbach,793,SecondHalf,50,12.0,52,134,Borussia M.Gladbach,25042.0,Raúl Bobadilla,Goal,Successful,75.8,35.4,None,None,53.0,11.1,NaN,NaN,NaN,NaN,shot,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,Goal,Outside of box,Unknown,Right foot,False,False,False,False,False,False,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,False,False,False,False,None,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None
10721,6a0ca079279178a2ca3eed99,420871,2010-2011,Germany,Bundesliga,2010-11-13 14:30:00,finished,12,282,FC Koln,134,Borussia M.Gladbach,825,SecondHalf,53,34.0,55,282,FC Koln,6040.0,Lukas Podolski,SavedShot,Successful,67.1,69.3,None,None,NaN,NaN,75.0,64.8,NaN,NaN,shot,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,True,False,False,Blocked,Outside of box,Unknown,Left foot,False,False,False,False,False,False,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,False,False,False,False,None,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None
10723,6a0ca079279178a2ca3eedba,420871,2010-2011,Germany,Bundesliga,2010-11-13 14:30:00,finished,12,282,FC Koln,134,Borussia M.Gladbach,860,SecondHalf,56,53.0,58,282,FC Koln,9124.0,Youssef Mohamad,MissedShots,Successful,89.9,41.5,None,None,58.2,73.6,NaN,NaN,431.0,6040.0,shot,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,Off Target,Penalty Area,Unknown,Head,False,False,False,False,False,False,False,True,False,False,False,None,False,False,None,False,False,None,False,False,False,False,False,False,False,None,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None
10725,6a0ca079279178a2ca3eee42,420871,2010-2011,Germany,Bundesliga,2010-11-13 14:30:00,finished,12,282,FC Koln,134,Borussia M.Gladbach,1002,SecondHalf,68,26.0,70,134,Borussia M.Gladbach,7367.0,Igor de Camargo,MissedShots,Successful,90.4,63.2,None,None,46.7,59.7,NaN,NaN,521.0,22825.0,shot,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,Off Target,Penalty Area,Unknown,Head,False,False,False,False,False,False,False,True,False,False,False,None,False,False,None,False,False,None,False,False,False,False,False,False,False,None,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None
10729,6a0ca079279178a2ca3eeece,420871,2010-2011,Germany,Bundesliga,2010-11-13 14:30:00,finished,12,282,FC Koln,134,Borussia M.Gladbach,1144,SecondHalf,77,27.0,79,282,FC Koln,77458.0,José Pierre Vunguidica,SavedShot,Successful,72.9,56.9,None,None,NaN,NaN,79.2,54.2,NaN,NaN,shot,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,True,False,False,Blocked,Outside of box,Unknown,Left foot,False,False,False,False,False,False,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,False,False,False,False,None,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None
10730,6a0ca079279178a2ca3eeed1,420871,2010-2011,Germany,Bundesliga,2010-11-13 14:30:00,finished,12,282,FC Koln,134,Borussia M.Gladbach,1147,SecondHalf,77,29.0,79,282,FC Koln,6040.0,Lukas Podolski,SavedShot,Successful,88.5,59.9,None,None,NaN,NaN,90.3,59.0,805.0,31975.0,shot,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,True,False,False,False,Blocked,Penalty Area,Unknown,Right foot,False,False,False,False,False,False,False,True,False,False,False,None,False,False,None,False,False,None,False,False,False,False,False,False,False,None,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None
10732,6a0ca079279178a2ca3eef09,420871,2010-2011,Germany,Bundesliga,2010-11-13 14:30:00,finished,12,282,FC Koln,134,Borussia M.Gladbach,1205,SecondHalf,80,43.0,82,282,FC Koln,38287.0,Kevin Pezzoni,SavedShot,Successful,92.9,60.6,None,None,49.7,30.6,99.4,52.9,622.0,31975.0,shot,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,On Target,Penalty Area,Unknown,Head,False,False,False,False,False,False,False,True,False,False,False,None,False,False,None,False,False,None,False,False,False,False,False,False,False,None,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None
10736,6a0ca079279178a2ca3eef36,420871,2010-2011,Germany,Bundesliga,2010-11-13 14:30:00,finished,12,282,FC Koln,134,Borussia M.Gladbach,1254,SecondHalf,86,14.0,88,282,FC Koln,77458.0,José Pierre Vunguidica,SavedShot,Successful,72.9,53.4,None,None,NaN,NaN,85.6,51.4,NaN,NaN,shot,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False,False,False,Blocked,Outside of box,Unknown,Right foot,False,False,False,False,False,False,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,False,False,False,False,None,False,False,False,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,None,False,False,False,None,False,False,None

In [37]:
for stat in ['shot_result', 'shot_situation', 'shot_zone', 'shot_body_part']:
    display(shot_events[(shot_events['game_id'] == 420871)].groupby('team')[stat].value_counts())

team                 shot_result
Borussia M.Gladbach  Off Target      9
                     Blocked         7
                     Goal            4
FC Koln              Blocked        11
                     Off Target      5
                     On Target       3
Name: count, dtype: int64

team                 shot_situation
Borussia M.Gladbach  Unknown           9
                     Open Play         6
                     Fastbreak         4
                     Set Pieces        1
FC Koln              Unknown           8
                     Open Play         6
                     Set Pieces        5
Name: count, dtype: int64

team                 shot_zone
Borussia M.Gladbach  Outside of box    13
                     Penalty Area       7
FC Koln              Penalty Area      10
                     Outside of box     8
                     6-yard box         1
Name: count, dtype: int64

team                 shot_body_part
Borussia M.Gladbach  Right foot        18
                     Head               2
FC Koln              Left foot          8
                     Right foot         7
                     Head               4
Name: count, dtype: int64

In [42]:
shot_events[shot_events['shot_situation'] == 'Unknown']['game_id'].value_counts().index.tolist()

[420871,
 724033,
 621276,
 621286,
 621392,
 328126,
 420825,
 421116,
 421179,
 723955,
 328056,
 328169,
 328302,
 420808,
 421234,
 509623,
 509625,
 509711,
 510157,
 621122,
 621306,
 621414,
 723789,
 723817,
 723862,
 723914,
 723919,
 723966,
 723969,
 724037,
 328085,
 328179,
 328219,
 328234,
 328238,
 328266,
 328316,
 420815,
 420999,
 421032,
 421056,
 421230,
 421233,
 421275,
 421294,
 509599,
 509662,
 509758,
 509837,
 510020,
 510113,
 621189,
 621260,
 621278,
 621355,
 723796,
 723816,
 723871,
 723878,
 723971,
 723995,
 724001,
 724002,
 328000,
 328034,
 328055,
 328124,
 328147,
 328225,
 328268,
 328286,
 420785,
 420798,
 420829,
 420849,
 420935,
 421060,
 421101,
 421181,
 421254,
 421276,
 421293,
 421300,
 509546,
 509549,
 509571,
 509726,
 509766,
 509969,
 510024,
 510048,
 510060,
 621167,
 621179,
 621193,
 621202,
 621219,
 621231,
 621290,
 621322,
 621371,
 723745,
 723751,
 723761,
 723828,
 723849,
 723851,
 723860,
 723866,
 723930,
 723947,
 723974,
 723983,
 723989,
 724018,
 327998,
 328025,
 328030,
 328037,
 328050,
 328051,
 328088,
 328095,
 328101,
 328107,
 328135,
 328146,
 328157,
 328173,
 328204,
 328257,
 328284,
 328300,
 328311,
 420809,
 420817,
 420821,
 420852,
 420876,
 421065,
 421082,
 421258,
 421260,
 509547,
 509584,
 509586,
 509730,
 509811,
 509830,
 509953,
 509976,
 509980,
 509988,
 509989,
 510010,
 510046,
 510127,
 510161,
 621132,
 621150,
 621163,
 621171,
 621186,
 621195,
 621239,
 621240,
 621258,
 621269,
 621327,
 621376,
 621387,
 723754,
 723758,
 723770,
 723777,
 723785,
 723810,
 723813,
 723819,
 723841,
 723889,
 723893,
 723908,
 723927,
 723942,
 723961,
 723962,
 723967,
 724006,
 724017,
 724029,
 724039,
 724045,
 724046,
 328061,
 328068,
 328093,
 328114,
 328117,
 328119,
 328121,
 328127,
 328134,
 328141,
 328143,
 328144,
 328168,
 328218,
 328240,
 328246,
 328270,
 328290,
 328296,
 328301,
 328305,
 328318,
 420764,
 420767,
 420768,
 420778,
 420788,
 420791,
 420796,
 420828,
 420831,
 420859,
 420903,
 420955,
 420994,
 421063,
 421080,
 421088,
 421095,
 421114,
 421119,
 421129,
 421134,
 421148,
 421248,
 421259,
 421271,
 421287,
 421295,
 509550,
 509658,
 509684,
 509742,
 509784,
 509822,
 509879,
 509910,
 509929,
 509930,
 509991,
 510009,
 510011,
 510054,
 510079,
 510106,
 510109,
 510114,
 510115,
 510138,
 510150,
 621146,
 621152,
 621173,
 621200,
 621205,
 621206,
 621212,
 621222,
 621227,
 621230,
 621233,
 621246,
 621247,
 621262,
 621265,
 621296,
 621299,
 621310,
 621311,
 621318,
 621386,
 621426,
 723697,
 723760,
 723790,
 723795,
 723821,
 723834,
 723837,
 723848,
 723850,
 723858,
 723864,
 723870,
 723877,
 723925,
 723932,
 723933,
 723957,
 723960,
 723972,
 723975,
 723992,
 723993,
 724027,
 724028,
 724043,
 328009,
 328020,
 328023,
 328031,
 328038,
 328042,
 328048,
 328066,
 328080,
 328091,
 328109,
 328125,
 328128,
 328131,
 328139,
 328165,
 328167,
 328181,
 328193,
 328207,
 328216,
 328220,
 328229,
 328239,
 328241,
 328244,
 328245,
 328253,
 328255,
 328267,
 328273,
 328282,
 328297,
 328298,
 328299,
 420762,
 420763,
 420771,
 420773,
 420774,
 420812,
 420816,
 420832,
 420833,
 420835,
 420841,
 420842,
 420869,
 420901,
 420907,
 420915,
 420929,
 420967,
 420975,
 420988,
 421018,
 421034,
 421047,
 421076,
 421092,
 421102,
 421128,
 421156,
 421232,
 421241,
 421246,
 421261,
 421281,
 421290,
 509553,
 509567,
 509570,
 509576,
 509603,
 509657,
 509688,
 509729,
 509760,
 509762,
 509775,
 509781,
 509798,
 509799,
 509828,
 509864,
 509865,
 509876,
 509892,
 509933,
 509955,
 509971,
 510018,
 510025,
 510036,
 510097,
 510123,
 510152,
 510158,
 510160,
 510162,
 621125,
 621137,
 621144,
 621149,
 621151,
 621157,
 621160,
 621209,
 621234,
 621238,
 621256,
 621303,
 621335,
 621337,
 621340,
 621342,
 621345,
 621347,
 621365,
 621372,
 621419,
 723695,
 723696,
 723755,
 723756,
 723762,
 723779,
 723782,
 723783,
 723791,
 723799,
 723800,
 723807,
 723815,
 723824,
 723825,
 723832,
 723840,
 723842,
 723873,
 723880,
 723883,
 723902,
 723910,
 723912,
 723934,
 723937,
 723938,
 723941,
 723953,
 723954,
 723964,
 723965,
 723979,
 723985,
 723987,
 723998,
 724000,
 724008,
 724022,
 724030,
 724031,
 724032,
 327997,
 327999,
 328002,
 328003,
 328007,
 328010,
 328046,
 328047,
 328049,
 328058,
 328062,
 328071,
 328072,
 328098,
 328099,
 328105,
 328111,
 328129,
 328133,
 328158,
 328162,
 328163,
 328172,
 328184,
 328201,
 328206,
 328222,
 328230,
 328247,
 328249,
 328260,
 328264,
 328278,
 328288,
 328294,
 420757,
 420760,
 420766,
 420770,
 420772,
 420777,
 420793,
 420794,
 420803,
 420807,
 420813,
 420814,
 420822,
 420827,
 420834,
 420840,
 420846,
 420851,
 420854,
 420878,
 420895,
 420898,
 420918,
 420919,
 420926,
 420928,
 420936,
 420939,
 420942,
 420977,
 420981,
 420983,
 420985,
 421000,
 421020,
 421023,
 421026,
 421041,
 421045,
 421078,
 421094,
 421106,
 421167,
 421180,
 421189,
 421227,
 421231,
 421240,
 421256,
 421288,
 421291,
 509548,
 509564,
 509568,
 509598,
 509608,
 509648,
 509687,
 509699,
 509755,
 509765,
 509802,
 509820,
 509832,
 509839,
 509881,
 509919,
 509922,
 509935,
 509936,
 509938,
 509947,
 509950,
 509957,
 509962,
 509973,
 509974,
 509995,
 510006,
 510007,
 510027,
 510061,
 510062,
 510075,
 510092,
 510099,
 510100,
 510101,
 510103,
 510118,
 510120,
 510124,
 510131,
 510140,
 510141,
 510146,
 510156,
 510163,
 621134,
 621139,
 621140,
 621159,
 621164,
 621168,
 621176,
 621177,
 621191,
 621201,
 621208,
 621210,
 621223,
 621235,
 621237,
 621242,
 621244,
 621245,
 621249,
 621251,
 621257,
 621261,
 621281,
 621288,
 621293,
 621305,
 621309,
 621315,
 621316,
 621326,
 621330,
 621339,
 621341,
 621368,
 621374,
 621380,
 621381,
 621390,
 621394,
 621406,
 621408,
 621412,
 621413,
 621418,
 621424,
 621428,
 723742,
 723746,
 723757,
 723765,
 723769,
 723775,
 723776,
 723778,
 723780,
 723797,
 723798,
 723802,
 723803,
 723806,
 723818,
 723823,
 723829,
 723833,
 723846,
 723856,
 723867,
 723875,
 723881,
 723882,
 723888,
 723896,
 723898,
 723899,
 723900,
 723905,
 723906,
 723915,
 723921,
 723923,
 723924,
 723928,
 723929,
 723944,
 723948,
 723949,
 723952,
 723978,
 723980,
 723982,
 723994,
 724003,
 724007,
 724019,
 724020,
 724021,
 724040,
 328004,
 328016,
 328017,
 328021,
 328022,
 328024,
 328029,
 328040,
 328054,
 328064,
 328070,
 328075,
 328076,
 328079,
 328082,
 328083,
 328089,
 328112,
 328122,
 328180,
 328187,
 328189,
 328192,
 328200,
 328203,
 328276,
 328279,
 328293,
 328304,
 328308,
 328309,
 328319,
 420775,
 420779,
 420781,
 420800,
 420805,
 420819,
 420824,
 420836,
 420844,
 420848,
 420858,
 420864,
 420866,
 420875,
 420890,
 420909,
 420910,
 420921,
 420923,
 420925,
 420991,
 421053,
 421054,
 421062,
 421069,
 421085,
 421091,
 421103,
 421109,
 421118,
 421121,
 421131,
 421154,
 421158,
 421164,
 421183,
 421187,
 421257,
 421263,
 421268,
 509551,
 509581,
 509591,
 509592,
 509622,
 509635,
 509666,
 509676,
 509677,
 509679,
 509682,
 509685,
 509690,
 509702,
 509704,
 509772,
 509779,
 509806,
 509815,
 509844,
 509849,
 509871,
 509903,
 509908,
 509913,
 509963,
 509967,
 509977,
 509993,
 509998,
 510002,
 510013,
 510023,
 510057,
 510080,
 510084,
 510085,
 510104,
 510110,
 510111,
 510122,
 510128,
 510129,
 510132,
 510134,
 510155,
 621135,
 621154,
 621155,
 621162,
 621165,
 621175,
 621181,
 621183,
 621185,
 621198,
 621207,
 621217,
 621221,
 621224,
 621226,
 621229,
 621252,
 621266,
 621283,
 621291,
 621294,
 621297,
 621301,
 621323,
 621324,
 621329,
 621333,
 621349,
 621361,
 621370,
 621382,
 621399,
 621402,
 621405,
 621409,
 621410,
 621416,
 621420,
 621421,
 621422,
 621425,
 621427,
 621429,
 621432,
 723699,
 723701,
 723747,
 723749,
 723750,
 723766,
 723784,
 723788,
 723822,
 723827,
 723844,
 723853,
 723855,
 723863,
 723865,
 723868,
 723884,
 723903,
 723904,
 723911,
 723916,
 723920,
 723922,
 723940,
 723946,
 723959,
 723981,
 723988,
 723991,
 724004,
 724005,
 724009,
 724010,
 724012,
 724013,
 724023,
 724026,
 724044,
 327995,
 328006,
 328008,
 328012,
 328018,
 328027,
 328028,
 328033,
 328039,
 328045,
 328053,
 328057,
 328087,
 328090,
 328096,
 328100,
 328106,
 328118,
 328120,
 328130,
 328132,
 328150,
 328164,
 328170,
 328171,
 328188,
 328205,
 328211,
 328221,
 328224,
 328226,
 328228,
 328236,
 328252,
 328256,
 328259,
 328263,
 328274,
 328295,
 328306,
 420780,
 420782,
 420784,
 420790,
 420804,
 420806,
 420818,
 420823,
 420830,
 420837,
 420839,
 420880,
 420882,
 420885,
 420887,
 420905,
 420916,
 420956,
 420996,
 421022,
 421028,
 421058,
 421087,
 421090,
 421111,
 421120,
 421130,
 421137,
 421139,
 421140,
 421151,
 421159,
 421165,
 421168,
 421169,
 421172,
 421178,
 421186,
 421245,
 421255,
 421266,
 421267,
 421270,
 421278,
 421286,
 509566,
 509579,
 509606,
 509612,
 509617,
 509638,
 509640,
 509651,
 509705,
 509708,
 509714,
 ...]

In [38]:
raw_events = pd.DataFrame(list(db[mongo_config.get('collection').get('collection_raw_events')].find({'game_id': 420871})))

In [39]:
raw_events

,_id,game_id,away_team_id,away_team_name,competition_country,competition_name,game_date,game_status,home_team_id,home_team_name,season,week,period,minute,second,expanded_minute,type,outcome_type,team_id,team,player_id,player,x,y,end_x,end_y,goal_mouth_y,goal_mouth_z,blocked_x,blocked_y,qualifiers,is_touch,is_shot,is_goal,card_type,related_event_id,related_player_id,event_idx
0,6a0aadde0113f547daff6cc4,420871,134,Borussia M.Gladbach,Germany,Bundesliga,2010-11-13 14:30:00,finished,282,FC Koln,2010-2011,12,FirstHalf,0,0.0,0,Start,Successful,282,FC Koln,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,[],False,None,None,NaN,NaN,NaN,0
1,6a0aadde0113f547daff6cc5,420871,134,Borussia M.Gladbach,Germany,Bundesliga,2010-11-13 14:30:00,finished,282,FC Koln,2010-2011,12,FirstHalf,0,0.0,0,Start,Successful,134,Borussia M.Gladbach,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,[],False,None,None,NaN,NaN,NaN,1
2,6a0aadde0113f547daff6cc6,420871,134,Borussia M.Gladbach,Germany,Bundesliga,2010-11-13 14:30:00,finished,282,FC Koln,2010-2011,12,FirstHalf,0,0.0,0,Pass,Successful,282,FC Koln,19279.0,Milivoje Novakovic,49.6,50.6,49.0,53.4,NaN,NaN,NaN,NaN,"[{'type': {'displayName': 'Length', 'value': 2...",True,None,None,NaN,NaN,NaN,2
3,6a0aadde0113f547daff6cc7,420871,134,Borussia M.Gladbach,Germany,Bundesliga,2010-11-13 14:30:00,finished,282,FC Koln,2010-2011,12,FirstHalf,0,2.0,0,Pass,Successful,282,FC Koln,6040.0,Lukas Podolski,49.0,53.4,37.8,46.3,NaN,NaN,NaN,NaN,"[{'type': {'displayName': 'Angle', 'value': 21...",True,None,None,NaN,NaN,NaN,3
4,6a0aadde0113f547daff6cc8,420871,134,Borussia M.Gladbach,Germany,Bundesliga,2010-11-13 14:30:00,finished,282,FC Koln,2010-2011,12,FirstHalf,0,5.0,0,Pass,Successful,134,Borussia M.Gladbach,21564.0,Tobias Levels,19.4,28.0,26.0,11.4,NaN,NaN,NaN,NaN,"[{'type': {'displayName': 'PassEndY', 'value':...",True,None,None,NaN,NaN,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1331,6a0aadde0113f547daff71f7,420871,134,Borussia M.Gladbach,Germany,Bundesliga,2010-11-13 14:30:00,finished,282,FC Koln,2010-2011,12,SecondHalf,90,36.0,92,End,Successful,134,Borussia M.Gladbach,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,[],False,None,None,NaN,NaN,NaN,1331
1332,6a0aadde0113f547daff71f8,420871,134,Borussia M.Gladbach,Germany,Bundesliga,2010-11-13 14:30:00,finished,282,FC Koln,2010-2011,12,PostGame,0,0.0,2,End,Successful,282,FC Koln,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,[],False,None,None,NaN,NaN,NaN,1332
1333,6a0aadde0113f547daff71f9,420871,134,Borussia M.Gladbach,Germany,Bundesliga,2010-11-13 14:30:00,finished,282,FC Koln,2010-2011,12,PostGame,0,0.0,2,End,Successful,134,Borussia M.Gladbach,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,[],False,None,None,NaN,NaN,NaN,1333
1334,6a0aadde0113f547daff71fa,420871,134,Borussia M.Gladbach,Germany,Bundesliga,2010-11-13 14:30:00,finished,282,FC Koln,2010-2011,12,PreMatch,0,0.0,0,FormationSet,Successful,134,Borussia M.Gladbach,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,[{'type': {'displayName': 'TeamPlayerFormation...,False,None,None,NaN,NaN,NaN,1334
1335,6a0aadde0113f547daff71fb,420871,134,Borussia M.Gladbach,Germany,Bundesliga,2010-11-13 14:30:00,finished,282,FC Koln,2010-2011,12,PreMatch,0,0.0,0,FormationSet,Successful,282,FC Koln,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"[{'type': {'displayName': 'PlayerPosition', 'v...",False,None,None,NaN,NaN,NaN,1335

In [ ]:
shot_events.groupby("shot_situation")["shot_goal"].agg(["count", "sum", "mean"])

In [ ]:
shot_events['shot_zone'].value_counts(normalize=True, dropna=False)

In [ ]:
shot_events.groupby("shot_zone")["shot_goal"].agg(["count", "sum", "mean"])

In [ ]:
shot_events['shot_body_part'].value_counts(normalize=True, dropna=False)

In [ ]:
shot_events.groupby("shot_body_part")["shot_goal"].agg(["count", "sum", "mean"])

In [ ]:
def season_goals(df: pd.DataFrame, season: str,
                 category: str, plot_type: str = "Goals") -> pd.DataFrame:
    
    season_df = df[df['season'] == season]
    if plot_type == "Goals":
        df = season_df[season_df["shot_goal"]].reset_index(drop=True)
        pitch = VerticalPitch(
                    half=True,
                    pitch_type="opta",
                    pitch_color='#aabb97',
                    line_color='white', 
                    stripe=True)
    
    else:
        df = season_df[season_df["shot_goal"] == False]
        pitch = Pitch(
                    pitch_type="opta",
                    pitch_color='#aabb97',
                    line_color='white', 
                    stripe=True)

    
    if category == "shot_body_part":
        colors = {
            "Right foot": "#2563EB",        # blue
            "Left foot": "#16A34A",         # green
            "Head": "#F97316",              # orange
            "Other body parts": "#7C3AED",  # purple
        }

    elif category == "shot_situation":
        colors = {
            "Open Play": "#2563EB",     # blue
            "Set Pieces": "#DC2626",    # red
            "Fastbreak": "#F59E0B",     # amber
            "Penalty": "#7C3AED",       # purple
            "Own Goal": "#111827",      # near black
            "Unknown": "#6B7280",       # gray
        }

    elif category == "shot_zone":
        colors = {
            "6-yard box": "#DC2626",       # red
            "Penalty Area": "#2563EB",     # blue
            "Outside of box": "#16A34A",   # green
            "Unknown": "#6B7280",          # gray
        }

    


    fig, ax = pitch.draw(figsize=(10, 7))

    for value, group in df.groupby(category, dropna=False):
        label = "Unknown" if pd.isna(value) else value
        pitch.scatter(
            group["x"],
            group["y"],
            ax=ax,
            s=45,
            color=colors.get(value, "#7f7f7f"),
            alpha=0.6,
            edgecolors="none",
            label=label,
        )

    ax.set_title(f"Goal Locations by {category} | {season}", fontsize=16)
    ax.legend(loc="upper left", frameon=True)

    plt.show()

In [ ]:
seasons = shot_events['season'].unique()

for season in seasons:
    season_goals(df=shot_events, season=season, category="shot_body_part")
    season_goals(df=shot_events, season=season, category="shot_situation")
    season_goals(df=shot_events, season=season, category="shot_zone")

In [ ]:

for season in seasons:
    season_goals(df=shot_events, season=season, category="shot_body_part", plot_type="Non-Goals")
    season_goals(df=shot_events, season=season, category="shot_situation", plot_type="Non-Goals")
    season_goals(df=shot_events, season=season, category="shot_zone", plot_type="Non-Goals")